### ISSUE TITLE
show IP address in windows tile 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#15]
```
display IP address of session along with session name in window title.

```

Original issue reported on code.google.com by `anu...@gmail.com` on 12 May 2010 at 6:06

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
