### ISSUE TITLE
Pageant support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#159]
```
It would be great if SuperPutty would check if the Pageant agent is running and 
all configured keys are loaded.
```

Original issue reported on code.google.com by `tom.ribb...@gmail.com` on 29 Jun 2012 at 12:33

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!

**Comment by zoff99** [comment]
why is this closed?
please simply add a feature (setting) to start pageant on startup with a configured keyfile.

new settings:
[x] : start pageant on startup?
________ : path to privatekey file

**Comment by jimradford** [comment]
It was closed because it was reported in 2015, migrated from google code. If you really really want to have this issue revisited please read and follow the instructions in the following document: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues
