### ISSUE TITLE
Enhancement Requests

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#163]
```
Couple of enhancements I can think of

1. Detaching a terminal tab as a separate window
2. Moving a tab from one SuperPutty window to another SuperPutty window.
3. Option to open a new session (which is not in the saved session list) 
   in tab.
```

Original issue reported on code.google.com by `srix4oth...@gmail.com` on 4 Jul 2012 at 4:32

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
