### ISSUE TITLE
Upgrade program from within the application.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#204]
```
It would be great to add an option to upgrade the version of the program from 
within the application, or even better to be notified if a new version is 
available and given the choice to upgrade.  Right now, I need to subscribe to 
the RSS feed and upgrade the program manually.
```

Original issue reported on code.google.com by `switchfo...@gmail.com` on 20 Aug 2012 at 4:20

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
