### ISSUE TITLE
Add support for SSL Connection.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#244]
```
add support for SSL-crypted raw connection.
Like "openssl s_client ..."
So connection to HTTPS, SMTPS.. Server are possible

Thanks,
Sascha

```

Original issue reported on code.google.com by `inusasha...@googlemail.com` on 9 Oct 2012 at 2:10

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
