### ISSUE TITLE
Again keyboard focus doesn't return to putty tab when switching to SP window

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#246]
```
What steps will reproduce the problem?
1. Switch to a different program via Alt-Tab or the mouse
2. Alt-Tab or mouse click back to SuperPuTTY
3. I can't to type into the current Putty tab (see screenshot)

What is the expected output? What do you see instead?
Expected output is the results of whatever you tried to type into the Putty tab.
Instead, nothing happens until I click in the Putty tab to give it keyboard 
focus.

What version of the product are you using? On what operating system?
1.3.0.11

Please provide any additional information below.
It is not duplicate of Issue 152

```

Original issue reported on code.google.com by `click2ru...@gmail.com` on 11 Oct 2012 at 3:19

Attachments:
* [No_Focus_After_Swithing_Back_To_SP_Window_.png](https://storage.googleapis.com/google-code-attachments/superputty/issue-246/comment-0/No_Focus_After_Swithing_Back_To_SP_Window_.png)

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
