### ISSUE TITLE
SFTP and SCP

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#249]
```
Is it possible to add selection of scp and sftp ? In pscp this are -sftp and 
-scp params.


```

Original issue reported on code.google.com by `przem...@gmail.com` on 18 Oct 2012 at 8:48

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
