### ISSUE TITLE
Automatic logon with -pw password

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#258]
```
See the attached screenshot for more details!


sp version: 1.3.0.11 / Windows 7 Pro. SP1
```

Original issue reported on code.google.com by `strugare...@gmail.com` on 23 Nov 2012 at 2:19

Attachments:
* [sperror.png](https://storage.googleapis.com/google-code-attachments/superputty/issue-258/comment-0/sperror.png)

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
