### ISSUE TITLE
Full screen issue

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#265]
```
What steps will reproduce the problem?
1. Open SP with two tabs
2. Enter Full Screen
3. Close one tab

What is the expected output? What do you see instead?
Windows start bar will show up.
See image for more details!

What version of the product are you using? On what operating system?
SP 1.4.0.1 Win7SP1 64bit

```

Original issue reported on code.google.com by `strugare...@gmail.com` on 1 Dec 2012 at 9:26

Attachments:
* [fullscreenissue.jpg](https://storage.googleapis.com/google-code-attachments/superputty/issue-265/comment-0/fullscreenissue.jpg)

**Comment by jimradford** [comment]
This does not appear to be an issue with a current version of SuperPuTTY. Tested 1.4.0.7/Windows 10

Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
