### ISSUE TITLE
Type or paste multiple commands into the command bar at once

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#272]
```
I like to run multiple commands at once.  Currently I do this by copy/pasting a 
short script into putty command sender.  For example, if I paste a script from 
notepad all lines would get run on their own command line.
```

Original issue reported on code.google.com by `jrj4...@gmail.com` on 10 Dec 2012 at 5:48

**Comment by waukeerules** [comment]
I'd also like to see this functionality added to SuperPutty. I currently use MTPuTTY to paste a script in multiple sessions.

**Comment by jimradford** [comment]
I think this can be implemented:
I think I'll add a new button to the toolbar which will open up a dialog which you can open/paste/save/run the lines contained in the dialog just as you would with a single command sent via the command bar. 

Why a button opening a dialog you ask? Well the current implementation is simply a combobox which will not allow for paste detection/multiple line input.

Future enhancements might include a parser which would allow macros to be expanded, for example [HOSTNAME] could be replaced with the name of the host the command is being sent to then sent to the host.

**Comment by jimradford** [comment]
Added to v1.4.0.7
