### ISSUE TITLE
Please add quake style drop down for superputty

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#287]
```
I am saying with one hotkey...user should be able to switch b/w super-putty and 
other running windows.
```

Original issue reported on code.google.com by `siddhart...@gmail.com` on 30 Jan 2013 at 2:12

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
