### ISSUE TITLE
acknowledgements

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#318]
```
It would be nice to have those who added patches like myself some 
acknowledgement on the about screen or somewhere ;)
```

Original issue reported on code.google.com by `djtrem...@gmail.com` on 21 Apr 2013 at 3:56

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
