### ISSUE TITLE
Customize Toolbars

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#323]
```
I want to drag toolbars so they can be next to each other.  I also want to add 
and remove buttons from the toolbars.
```

Original issue reported on code.google.com by `andrewmw...@gmail.com` on 24 Apr 2013 at 6:57

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
