### ISSUE TITLE
Layout Not Loading

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#342]
```
Hi 

this my just be me but i can't get your layouts to work i have saved and loaded 
many times and it just wont work i am using superputty 1.4.0.4

the layouts are in the menu but wont load sure it could be my system i am 
running windows 7 64 bit pro 14 GB memory 

i have attached the file it makes but it just wont load it when asked
```

Original issue reported on code.google.com by `jaeagl...@gmail.com` on 12 Jun 2013 at 3:18

Attachments:
* [All Switches.xml](https://storage.googleapis.com/google-code-attachments/superputty/issue-342/comment-0/All Switches.xml)

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
