### ISSUE TITLE
Superputty crash on close and session save

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#346]
```
What steps will reproduce the problem?
1. When closing superputty
2. When saving a change to a session
3.

What is the expected output? What do you see instead?  I want to close program 
i get the error.  I want to save a change to a session I get the error.  The 
only way i can close supperputty at that point is to end through task manager


What version of the product are you using? On what operating system?
1.3.0.11 on Win7 Enterprise

Please provide any additional information below.

```

Original issue reported on code.google.com by `paul...@windstream.net` on 3 Jul 2013 at 5:43

Attachments:
* [supperputtyerror.jpg](https://storage.googleapis.com/google-code-attachments/superputty/issue-346/comment-0/supperputtyerror.jpg)

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
