### ISSUE TITLE
File Transfer will not work if home directory is not in /home/User

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#348]
```
Please describe in as much detail as possible the feature you would like to
see added

when I tried to use the "File Transfer" in the session manager, the file 
transfer module will not work if my home directory is not in /home/<Username>
```

Original issue reported on code.google.com by `eric...@gmail.com` on 5 Jul 2013 at 2:43

**Comment by jimradford** [comment]
Yes it is!

**Comment by breversa** [comment]
I know there is now (as of 1.4.0.8) an option to globally set the homedir prefix, but is there an option to specify the homedir per session ?

My work requires connecting as (for example) :
* user1, whose homedir is /home1/user1
* user2, whose homedir is /home1/user2_suffix.

File transfer fails with "Unable to open /home1/user2".
