### ISSUE TITLE
Unable to use SCP using PSCP

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#349]
```
What steps will reproduce the problem?
1. Add PSCP for using SCP
2. Try to connect


What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?
On the left hand side I can see my local machine console, however on the right 
hand side, I am unable to view the remote machine. Instead an error message 
"Process Timed Out XXxxx" is displayed. Has anyone integrated PSCP and used it

Please provide any additional information below.

```

Original issue reported on code.google.com by `asheesh....@gmail.com` on 5 Jul 2013 at 11:54

Attachments:
* [Error.docx](https://storage.googleapis.com/google-code-attachments/superputty/issue-349/comment-0/Error.docx)

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
