### ISSUE TITLE
Linux/Mono support (I can dream :)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#365]
```
Port the whole thing to Linux/Mono, using the Linux port of Putty.

This likely requires porting the Docking project as well.
```

Original issue reported on code.google.com by `h...@toptranslation.com` on 31 Aug 2013 at 5:43

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
