### ISSUE TITLE
PSCP is not working thru supperputty session

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#369]
```
What steps will reproduce the problem?
1.Configure pscp.exe within supperputty settings
2.Initiate a file transfer
3.

What is the expected output? What do you see instead?
File transferred.

What version of the product are you using? On what operating system?
Supperputty v1.3/Windows 7

Please provide any additional information below.

```

Original issue reported on code.google.com by `shree...@gmail.com` on 14 Sep 2013 at 9:05

Attachments:
* [pscp-not-working-thru-supperputty.png](https://storage.googleapis.com/google-code-attachments/superputty/issue-369/comment-0/pscp-not-working-thru-supperputty.png)

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
