### ISSUE TITLE
Can't bring back menu bar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#374]
```
What steps will reproduce the problem?
1. Hide menu bar
2. There is no way to bring back menu bar
3.
```

Original issue reported on code.google.com by `Pitsanu1...@gmail.com` on 24 Sep 2013 at 2:49

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
