### ISSUE TITLE
Select multiple hosts from the sessions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#375]
```
In Putty CM you can select multiple hosts by clicking 1 then holding the shift 
key and selecting say 5 down and they all get highlighted to open.

```

Original issue reported on code.google.com by `proy...@gmail.com` on 2 Oct 2013 at 10:39

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
