### ISSUE TITLE
NullReferenceException on first install

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#379]
```
What steps will reproduce the problem?
1. copy as (call from session)
2.
3.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.

```

Original issue reported on code.google.com by `durovi...@gmail.com` on 8 Oct 2013 at 9:29

Attachments:
* [error.png](https://storage.googleapis.com/google-code-attachments/superputty/issue-379/comment-0/error.png)

**Comment by jimradford** [comment]
So as it turns out the problem is with the ImageList being excluded from loading on first run, This was a problem in circumstances where there were existing sessions to load. The default imagelist was being clobbered on first run.
