### ISSUE TITLE
Don´t autorestore last opened sessions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#384]
```
It seems that SuperPutty always opens the sessions that have been opened the 
last time. While this is basically a good thing, it would be good, if this 
behaviour could be configured or if there was a way to close all sessions at 
once.

```

Original issue reported on code.google.com by `larsen...@web.de` on 28 Oct 2013 at 12:01

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
