### ISSUE TITLE
Importing Sessions from PuTTY CM, Passwords not passed into SuperPuTTY

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#386]
```
What steps will reproduce the problem?

1. Export PuTTY CM database as XML (Have passwords added to each individually 
session, so that you are logged in automatically)
2. In SuperPuTTY, Import Session from PuTTY CM Export
3. Notice that none of the passwords were passed in the extra arguments 



What is the expected output? What do you see instead?

I expected to see -pw mypassword entered into the Extra Argument field so that 
I am automatically logged in.



What version of the product are you using? On what operating system?

1.4.0.4 on Windows 7 Home Premium 64 bit, unsure of PuTTY CM version, but most 
up to date one.



Please provide any additional information below.

This isn't really a defect, but if there was an easy workaround that would be 
nice. I have dozens of servers that I do not want to have passwords for 
manually. In the XML export from PuTTY CM, passwords are contained in 
<password>mypassword</password>, and in superPuTTY is it contained in 
ExtraArgs="mypassword"/>





Thanks
```

Original issue reported on code.google.com by `seman....@gmail.com` on 30 Oct 2013 at 5:24

**Comment by zhudock** [comment]
I agree that this would be a useful feature. Alternatively, creating a Session.password property, and leaving ExtraArgs alone would be another option. From there, SuperPutty could automatically add -pw Session.password to the putty command on launch

**Comment by jimradford** [comment]
Thanks for the feedback and report.

One glaring security consequence with using -pw password as a command line argument to putty which is a long living process under most use cases is that command line arguments can be readily visible in the process list which as you can imagine is not a very good thing. For password/security purposes I strongly urge users to use private key authentication where possible. See this HowTo: https://www.howtoforge.com/how-to-configure-ssh-keys-authentication-with-putty-and-linux-server-in-5-quick-steps I admit its painful at first, but once setup you'll never look back.
