### ISSUE TITLE
cache directories in file transfer mode

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#388]
```
please cache the entries of an directory.
This will provide a faster browsing. The loading of the entries can run in the 
background, or only with an manual update.
(like WinSCP)
```

Original issue reported on code.google.com by `inusasha...@googlemail.com` on 4 Nov 2013 at 7:15

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
