### ISSUE TITLE
support deleting of files in file transfer mode

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#389]
```
in file transfer mode, the user should able to delete files and directories 
from remote server.

```

Original issue reported on code.google.com by `inusasha...@googlemail.com` on 4 Nov 2013 at 7:19

**Comment by jimradford** [comment]
This is not possible with pscp, its simply to copy files between hosts. If you are looking for a full featured secure file manager look into WinSCP
