### ISSUE TITLE
Layout tab is still opening

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#409]
```
Ver 1.4.0.4.
Layout tab is still opening after fresh start. Is there any way how to save 
setting and keep this tab closed?
```

Original issue reported on code.google.com by `xsoft...@gmail.com` on 27 Jan 2014 at 9:40

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
