### ISSUE TITLE
Command history lost on exit

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#414]
```
I've been using SuperPutty for over 3 years and I love working on it.
Its tabbed browsing is excellent and saves me a lot of time.

Currently, when a session is closed, the command history is lost.
Can you please include a setting, so that user can choose if command history 
can be saved. While saving, we can limit the number of commands to be stored.
```

Original issue reported on code.google.com by `trevanth...@gmail.com` on 12 Feb 2014 at 1:36

Attachments:
* [20140211_SuperPutty_CommandHistory.png](https://storage.googleapis.com/google-code-attachments/superputty/issue-414/comment-0/20140211_SuperPutty_CommandHistory.png)

**Comment by jimradford** [comment]
See Issue #530
