### ISSUE TITLE
Integrate PuTTYNG into superputty

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#415]
```
Could you integrate PuTTYNG (https://github.com/rmcardle/PuTTYNG) into supper 
putty like PuTTY or KiTTY?

Thanks in advance,
Sinouplen.

```

Original issue reported on code.google.com by `sinoup...@gmail.com` on 12 Feb 2014 at 1:17

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
