### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#417]
```
Forever I have been looking for something that can do horizontal scrolling.  
I.e. a horizontal scrollbar at the bottom of the terminal window so that text 
will never wrap in the terminal.  Something like the attached.

Perhaps something like where in Putty-->config, under "Window", you can set 
"Columns" to something really large like 8000.  That would set the window 
buffer width that value on the remote machine, and the container of the 
terminal would be independently re-sizable and show the horizontal scrollbar.
```

Original issue reported on code.google.com by `ryanag...@gmail.com` on 18 Feb 2014 at 2:46

Attachments:
* [horizscroll.PNG](https://storage.googleapis.com/google-code-attachments/superputty/issue-417/comment-0/horizscroll.PNG)

**Comment by ronaldjeremy** [comment]
buuump 2 years later :)

**Comment by jimradford** [comment]
@ronaldjeremy Thanks for the Bump!

In putty no matter how wide you set the columns property it doesn't appear to add a horizontal scroll bar.

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
