### ISSUE TITLE
Hardcoded path

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#425]
```
What steps will reproduce the problem?
1. Restrict permissions to %userprofile%
2. Run superputty

What is the expected output? What do you see instead?
Attaching screenshot. I do not have e:\projects\dotnet... directory

What version of the product are you using? On what operating system?
Win 7 64, superputty 1.4.0.4

```

Original issue reported on code.google.com by `mirek.sz...@gmail.com` on 16 Apr 2014 at 7:24

Attachments:
* [tmp_2014-04-16 09_15_15-Application_ThreadException1493093841.png](https://storage.googleapis.com/google-code-attachments/superputty/issue-425/comment-0/tmp_2014-04-16 09_15_15-Application_ThreadException1493093841.png)

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
