### ISSUE TITLE
How to restore connection  file in putty connection manager

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#438]
```
Hello,

I am using MremoteNG i have save my connection data as xml file.
I need to restore it in Putty connection manger.

I have restore it in Putty connection manger but iam not able to view that 
connections.

Kindly do need full.
```

Original issue reported on code.google.com by `rajjang...@gmail.com` on 30 Jun 2014 at 11:20

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
