### ISSUE TITLE
Crash on 2008 R2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#450]
```
Extracted ZIP to a folder
tried launching the EXE but it fails.

ERROR

Faulting application name: SuperPutty.exe, version: 1.4.0.5, time stamp: 
0x53a4692c
Faulting module name: KERNELBASE.dll, version: 6.1.7601.18015, time stamp: 
0x50b8479b
Exception code: 0xe0434f4d
Fault offset: 0x0000000000009e5d
```

Original issue reported on code.google.com by `ja...@jaredjennings.org` on 14 Aug 2014 at 8:28

Attachments:
* [Report.wer](https://storage.googleapis.com/google-code-attachments/superputty/issue-450/comment-0/Report.wer)

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
