### ISSUE TITLE
System.InvalidOperationException when selecting a session from the dropdown list that has been closed already

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#451]
```
What steps will reproduce the problem?
- Open three sessions
- In the first one execute "sleep 10 && exit"
- Switch to the second one
- Open the dropdown list with all the opened sessions
- Wait for the first session to close
- When it has closed, select it´s entry from the list

What version of the product are you using? On what operating system?
1.4.0.4 on Windows 7, 64-bit

Please provide any additional information below.
Would need to check if the session is still there when opening it from the 
dropdown list.

```

Original issue reported on code.google.com by `larsen...@web.de` on 19 Aug 2014 at 8:01

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!

**Comment by larsen0815** [comment]
I was able to reproduce this problem in SuperPuTTY 1.4.0.8
See screenshot of error message.

![clipboard-1](https://cloud.githubusercontent.com/assets/2345512/12350258/4d264880-bb76-11e5-867f-aeb262ff17bb.png)
