### ISSUE TITLE
Application Thread Exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#453]
```
What steps will reproduce the problem?
1.Open SuperPutty 1.4.0.5, right click in sessions area
2.Click New Session
3. Fill out information for session, click save

What is the expected output? What do you see instead?
Expected to allow me to save session.  Image of what appears: 
http://s17.postimg.org/guysvwydr/8_21_2014_9_55_38_PM.png

What version of the product are you using? On what operating system?
1.4.0.5

Please provide any additional information below.

```

Original issue reported on code.google.com by `michaelc...@gmail.com` on 22 Aug 2014 at 3:03

Attachments:
* [8-21-2014 9-55-38 PM.png](https://storage.googleapis.com/google-code-attachments/superputty/issue-453/comment-0/8-21-2014 9-55-38 PM.png)

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
