### ISSUE TITLE
Application_ThreatException - System Cannot Find the File at [multiple sources]

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#455]
```
What steps will reproduce the problem?
1. Open SuperPuTTY
2. double-click on any session


What is the expected output? What do you see instead?
Open putty window for the selected device.
I get error dialog [screenshot attached].  Note there is no 
C:\users\jradford\.. on my system

What version of the product are you using? On what operating system?
Was 1.3, upgraded to newest stable 1.4.0.5, and get same message.

Please provide any additional information below.
Could not find same issue in search of existing documents.

```

Original issue reported on code.google.com by `mikenela...@gmail.com` on 22 Aug 2014 at 8:53

Attachments:
* [2014-08-21 - Application_ThreatException - System Cannot Find the File at [multiple].JPG](https://storage.googleapis.com/google-code-attachments/superputty/issue-455/comment-0/2014-08-21 - Application_ThreatException - System Cannot Find the File at [multiple].JPG)

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
