### ISSUE TITLE
Support for "-wt" (window title) argument for GNS3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#456]
```
GNS3 sends the -wt argument to PuTTY to name the console windows with the 
device hostname instead of the full executed command line.  The change can be 
made to ctlPuttyPanel.cs as shown below.

public override string Text
        {
            get
            {
                return base.Text;
            }
            set
            {
+                //127.0.0.1 -P 2101 -wt R1 -gns3 5 -skin 4
+                int iLoc = value.IndexOf("-wt ", 
StringComparison.CurrentCultureIgnoreCase);
+                if (iLoc >= 0)
+                {
+                    iLoc = iLoc + 4;
+                    int iLocEnd = value.IndexOf(" ", iLoc, 
StringComparison.CurrentCultureIgnoreCase);
+                    if (iLocEnd < 0)
+                        iLocEnd = value.Length;
+                    string sNewTitle = value.Substring(iLoc, iLocEnd - iLoc);
+                    this.TabText = sNewTitle;
+                    base.Text = sNewTitle;
+                }
+                else
+                {
                    this.TabText = value != null ? value.Replace("&", "&&") : value;
                    base.Text = value;
+                }

Thanks,
Helder.
```

Original issue reported on code.google.com by `hld...@gmail.com` on 25 Aug 2014 at 6:20

**Comment by 4SiB** [comment]
I have the same problem !
How fix this ? I install latest SuperPutty and I cannot use a -wt parameter.
SupperPutty not have a documentation of CLI parameters at DOC section !

**Comment by jimradford** [comment]
I don't see -wt as an optional parameter for putty, according to this list: https://documentation.help/PuTTY/using-general-opts.html 

Can someone explain why gns3 sends an invalid parameter?

**Comment by 4SiB** [comment]
Because :
1) It works on old version of SuperPutty
2) Documentation of SuperPutty at https://github.com/jimradford/superputty/wiki/Documentation#external-articles show us a video of configuring version with SuperPutty but this autor at his academy show more movies who use this -wt parameter.
3) GNS3 have included this -wt feature out-of-box, It's show here: https://youtu.be/_I0EjlUowog?t=341 (v1.4.0.9) and this works long ago... after update to latest version this stops works out-of-box :(

I know that putty.exe -load "Hostname" base on https://superuser.com/questions/1334309/putty-command-line-argument-to-change-title can change in Putty the window title.

**Comment by 4SiB** [comment]
I back with SuperPutty to 1.4.0.9, the archive version extract to C:\Program Files\GNS3
In SuperPutty options I use that exact C:\Program Files\GNS3\putty.exe and it's accept the -wt option. I think this is not a problem of SuperPutty but my update of GNS3 update it's internal version of build-in putty.exe who currently is breake - not change window title by -wt but accept it.

![image](https://user-images.githubusercontent.com/18070741/142945942-d96cb9cd-f1b9-48ae-91f2-c66abbae53d4.png)

When I run this gn3\putty.exe then I see the compiled version:
![image](https://user-images.githubusercontent.com/18070741/142946111-e77f15c3-b192-4dcf-9767-85dd5f14987e.png)

**Comment by 4SiB** [comment]
**SOLVED.
SuperPutty > Tools > Options > GUI tab > Tab Text: Dynamic**
And works perfect !

![image](https://user-images.githubusercontent.com/18070741/142951294-ffe1d7f0-9a78-490e-9896-ab277bf85d9d.png)

**Comment by jimradford** [comment]
Got it, that makes sense, you were using a custom build of putty. SuperPuTTY just passes the arguments along, to putty and doesn't eat them. Glad you got it working.
