### ISSUE TITLE
unable to do ssh to a server

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#461]
```
What steps will reproduce the problem?
1.when i enter details of server and login it gives me error
2.
3.

What is the expected output? What do you see instead?
it should login to server

What version of the product are you using? On what operating system?
the latest one 1.4.0.5

Please provide any additional information below.

```

Original issue reported on code.google.com by `bhardwaj...@gmail.com` on 17 Sep 2014 at 9:15

Attachments:
* [New Bitmap Image.bmp](https://storage.googleapis.com/google-code-attachments/superputty/issue-461/comment-0/New Bitmap Image.bmp)

**Comment by jimradford** [comment]
Check to make sure under F2 options the path/location to putty is configured correctly.

Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
