### ISSUE TITLE
Detection of disconnected tabs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#466]
```
Hello,
It would be helpful to detect disconnected tabs and display them with alternate 
icon/color. Also for such tabs context menu should be stripped.
And most usable is to restart session for such tabs by just pressing Enter 
(like in putty-nd)

Please consider this patches for implementation:
https://github.com/sepich/superputty/commit/d7abc32d70f37979eaef308a05f6510fab2f
c8c8

https://github.com/sepich/superputty/commit/f75d61385fc552d70ad7a6cd27d27dee3283
514d
```

Original issue reported on code.google.com by `i...@sepa.spb.ru` on 28 Sep 2014 at 11:25

**Comment by jimradford** [comment]
Can you consider rebasing those patches against the current codebase and submit a pull request?

Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
