### ISSUE TITLE
Remote Desktop (RDP) Support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#468]
```
Hi,

I know it's called "superputty" but I think it would be really useful to add 
Remote Desktop (RDP) support in the tool.

Even though network administrators usually manage network devices through SSH, 
there's often a Windows server somewhere we need to access too ;)

Thanks!
```

Original issue reported on code.google.com by `gabriel....@gmail.com` on 1 Oct 2014 at 1:58

**Comment by TheMaskedMan** [comment]
This would be awesome. Please make this happen!

**Comment by JeffWDH** [comment]
I'd like to vote for this as well.

There seems to be a MS RDP ActiveX control which could be utilized for this:

https://msdn.microsoft.com/en-us/library/aa383541%28v=vs.85%29.aspx

**Comment by madhusudhanane** [comment]
This would be a great value add for Super Putty.
