### ISSUE TITLE
Issue loading <file>.xml in Superputty that was created by putty connection manager

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#470]
```
What steps will reproduce the problem?
1.Try to import a <file>.xml in Superputty that was created by putty connection 
manager
2.
3.

What is the expected output? What do you see instead?
 Expect to load the connecttion database that was saved from putty CM
 Instead I get this error (see attached screenshot)

What version of the product are you using? On what operating system?
 I tried Super putty 
  1.3.0.11 and 1.4.0.4

Please provide any additional information below.

 

```

Original issue reported on code.google.com by `jf.fen...@gmail.com` on 2 Oct 2014 at 4:11

Attachments:
* [Capture.PNG](https://storage.googleapis.com/google-code-attachments/superputty/issue-470/comment-0/Capture.PNG)

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
