### ISSUE TITLE
Unnecessary PuTTY Icon in taskbar

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#475]
```
Unfortunately I can't tell how to reproduce this error (if it is one) but 
sometimes I get an additional PuTTY icon in my taskbar when I open a new 
session.


Win 7 (64bit), superputty 1.4.0.5, putty 0.63

```

Original issue reported on code.google.com by `m...@kbanause.com` on 16 Oct 2014 at 8:24

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
