### ISSUE TITLE
Windows 7 (64 Bit) - SuperPutty Opens, but can't see sessions properly or the session is not displayed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#484]
```
What steps will reproduce the problem?
1. Every time I open Super Putty application and open a session or sessions - 
I've tried many versions and still has the same issue.
2.
3.

What is the expected output? What do you see instead?

SuperPutty application opens, but I can't see the sessions properly open or the 
session opens, but can't see the session box at all.  I've re-adjusted my 
screen resolution and still no good.

What version of the product are you using? On what operating system?
Versions:
1.4.0.5
1.4.0.4
1.4.0.2
or 1.3.0.11

OS:
Windows 7 Enterprise
64 bit

Please provide any additional information below.

```

Original issue reported on code.google.com by `rudycast...@gmail.com` on 5 Dec 2014 at 9:16

Attachments:
* [super_putty_issue.PNG](https://storage.googleapis.com/google-code-attachments/superputty/issue-484/comment-0/super_putty_issue.PNG)

**Comment by deatheros** [comment]
Same issue for me, please advise. 
Putty sessions work properly, but Superputty is blank

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
