### ISSUE TITLE
Sometime when starting up a new ssh window the text is compressed to one side

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#489]
```
What steps will reproduce the problem?
1.Set the session window to autohide
2.Connect to one of the sessions in the list
3.Usually the first SSH window get compressed

What is the expected output? What do you see instead?
uncompressed text, works fine if you close it and open a new window.

What version of the product are you using? On what operating system?
SuperPutty v1.4.0.5, Windows 7

Please provide any additional information below.

```

Original issue reported on code.google.com by `simonleu...@gmail.com` on 16 Dec 2014 at 1:59

Attachments:
* [defect.png](https://storage.googleapis.com/google-code-attachments/superputty/issue-489/comment-0/defect.png)

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
