### ISSUE TITLE
Commands Not Working for multiple screens

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#491]
```
What steps will reproduce the problem?
1.Install
2.Open 2 Sessions
3.Issue Command in Commands Screen

What is the expected output? What do you see instead?
command to go to both sessions

What version of the product are you using? On what operating system?
1.4.0.5

Please provide any additional information below.
Accept Commands is checked in both sessions
```

Original issue reported on code.google.com by `gregorye...@gmail.com` on 19 Dec 2014 at 5:01

**Comment by fixedit** [comment]
okay so when you drag a tab. you will see the main icon in the center with all four sides. you have to drag the tab to that, not to the ones all the way at the edges of the tab. so if you want a seperate winow at the bottom you have to hover the tab over the bottom portion of the foursided icon. do not bring the tab (seperate window) all the way to the bottom of the main window. I am using ver. 1.4.0.6

**Comment by evanjtravis** [comment]
I'm the March 18 poster. I realize I was ambiguous in my phrasing. I wasn't using a separate window for the bottom half of the screen, but had the layout saved so that it opened with the tab configuration  illustrated in my previous post, with a group of tabs on the left and right sides, and one on the bottom. 

The commands propagate to the bottom tab only if during that session, they are dragged to the bottom of the window, not if they are loaded in that way from the layout file.

I am using version 1.4.0.6 (downloaded and installed mere moments ago).

**Comment by jimradford** [comment]
I have tried every way I can to reproduce this issue, using the steps to reproduce as well as trying all sorts of window configurations to no avail. Can anyone else confirm they are having issues with the command bar at all?

**Comment by evanjtravis** [comment]
I've included this image of my superputty instance to aid in finding the culprit. As you can see, the lower tab "ERROR" is not showing up in the list of tabs to send a command to.

![superputty-issue-491](https://cloud.githubusercontent.com/assets/9142617/10080472/72609188-62b5-11e5-9708-467f2ea497f7.png)

**Comment by evanjtravis** [comment]
I'm not able to upload the template file used for this session. Github isn't processing the file correctly, and It's not showing up as copy-pasted text either in the preview tab for writing a comment.

**Comment by jimradford** [comment]
@evanjtravis  Thanks for the update. 
I can now reproduce this It appears sessions that are docked outside of the tab windows e.g. on the top, left, bottom or right docking locations do not receive toolbar commands. These windows also do not show up in the session selector window.

**Comment by evanjtravis** [comment]
Thanks for the update. For now it's not a big deal in my work flow to repeat a command once, but it'd be nice for this to be fixed if I decide to create more elaborate layouts. :)

**Comment by jimradford** [comment]
@evanjtravis Finally had a few moments and got this fixed. Go crazy with your layouts and report back any troubles you find.

**Comment by jkldgoefgkljefogeg** [comment]
Is it possible to send the command to only 1 tab? I would like to save commonly used commands in the command bar, which does not need to be sent to all tabs.
