### ISSUE TITLE
Cant use on a computer with user join domain.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#492]
```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?
Superputyy cant open with the tab. putty open with new window

What version of the product are you using? On what operating system?
it's stable version in download page. i use window 7 32 bit with join domain 
user

Please provide any additional information below.
 with my private laptop it's Ok. but with my company password. i'm working with join domain user. i run superputyy and ssh to the server but it open a new window of putty not a tab of supperputty.
Please guide me to fix that.
```

Original issue reported on code.google.com by `kd02.min...@gmail.com` on 12 Jan 2015 at 2:28

Attachments:
* [issue with superputty.jpg](https://storage.googleapis.com/google-code-attachments/superputty/issue-492/comment-0/issue with superputty.jpg)

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
