### ISSUE TITLE
Cannot create new sessions.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#497]
```
What steps will reproduce the problem?
1. Unzip in a directory eg: c:\tools\SuperPutty-1.4.0.5
2. Choose putty and settings folder
3. Set the settings folder to the same one where putty is installed.
4. New Session -> Save -> Poof! Image show that there seems to be a hard coded 
directory c:\users\jradford
```

Original issue reported on code.google.com by `rouche@gmail.com` on 11 Feb 2015 at 2:24

Attachments:
* [2015-02-11_09-28-07.png](https://storage.googleapis.com/google-code-attachments/superputty/issue-497/comment-0/2015-02-11_09-28-07.png)

**Comment by jimradford** [comment]
This has been fixed I believe in more current versions. Please try with a current version and report any further issues.
