### ISSUE TITLE
Under bell / flashing support

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#503]
```
I don't know if this feature exists. I tried setting kitty up with superputty, 
and well I did flashing with bell. I didn't get a highlight or anything when I 
tried. It would really be useful. Could you add it please? :)
```

Original issue reported on code.google.com by `justinlh...@gmail.com` on 9 Mar 2015 at 3:50

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
