### ISSUE TITLE
Tab Names Not Saved in Layouts

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#506]
```
What steps will reproduce the problem?
1. Open Superputty.
2. Load Layout in either a new instance or in current instance.
3. Change tab names.
4. Save Layout.
5. Close Superputty.
6. Steps 1 and 2

What is the expected output? What do you see instead?
I expect to see the tab name changes from my previous layout save. Instead, the 
tabs default to their dynamic tab text.

What version of the product are you using? On what operating system?
SuperPutty-1.3.0.11
Windows 7

Please provide any additional information below.

```

Original issue reported on code.google.com by `evanjtra...@gmail.com` on 18 Mar 2015 at 2:20

**Comment by evanjtravis** [comment]
I am the original poster for this issue. This problem still exists in version 1.4.0.6

**Comment by jimradford** [comment]
@evanjtravis Thanks for the report. This is functionality we have never supported so I am changing its Label to enhancement. @joeyhub is doing some work in the underlying data structures so we will see how that shakes out and look at re-addressing this issue once those changes are finalized.

**Comment by evanjtravis** [comment]
I reread my original issue posting. With the static tab name option, I'm able to see the saved tab names on launch. My original thought was that the tab names were saved in the file, but weren't read correctly on launch, but it was just a configuration issue on my part trying to assign static names to dynamically named tabs.

By using the Static Tab Names setting, I'm able to get the functionality I want, and the Mixed setting is also pretty great. I guess the issue can change to communicating the differences between `static`, `dynamic`, and `mixed` to the end user to avoid confusion, but it seems like it's just me anyway. :P

**Comment by jimradford** [comment]
@evanjtravis Thanks for the update. I myself didn't even notice that option, it was something that was implemented probably years ago and I had forgotten about it. I'll be sure to document it in the Wiki.
