### ISSUE TITLE
Setting GUI opacity to 0 is non recoverable.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#509]
```
What steps will reproduce the problem?
1. In GUI tab set opacity to 0
2.
3.

What is the expected output? What do you see instead?
Makes window completely invisible without any chance of altering the setting 
back.


What version of the product are you using? On what operating system?
Current stable version 1.4.0.5 Windows 7

Please provide any additional information below.
Is there a config file or registry value that can be changed?

Russell Rockefeller
http://russellrockefeller.wordpress.com
Twitter @RockefellerRuss

```

Original issue reported on code.google.com by `digitalt...@gmail.com` on 4 Apr 2015 at 1:00

**Comment by jimradford** [comment]
I cannot imagine why anyone would want to set the opacity to 0 but some might so I'll leave that functionality in there. For those that DO change the value to 0 and want to be able to recover, simply open the application, click on the Taskbar Icon to ensure the application is in focus. hit the F2 function key which brings up the settings dialog and change the value to one more appropriate. Clicking on OK will then reset the settings and you should have your window visible with the correct opacity.
