### ISSUE TITLE
Close the current session by key combination

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#512]
```
Greetings,

It would be great if Ctrl+F4 combination would close the current active session 
on the screen.

Regards,
-Iulian
```

Original issue reported on code.google.com by `m...@surugiu-iulian.info` on 20 Apr 2015 at 4:02

**Comment by jimradford** [comment]
Under Tools->Options->Shortcuts you can assign Ctrl+F4 to the Close Tab action and it should give you what you want.
