### ISSUE TITLE
Exception in importing the saved session from file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#515]
```
What steps will reproduce the problem?
1.Go to File -> Import Sessions -> From File
2.Select the previously saved layout in the XML format.
3.Open

What is the expected output? What do you see instead?

The saved layout should open.
But the following exception is being popped up and the saved layout is not 
coming up:

Application_ThreadException
There is an error in XML document (4,2) -> System invalid operator exception.
What version of the product are you using? On what operating system?



```

Original issue reported on code.google.com by `shubhash...@gmail.com` on 29 Apr 2015 at 7:53

Attachments:
* [SuperputtyBugCapture.PNG](https://storage.googleapis.com/google-code-attachments/superputty/issue-515/comment-0/SuperputtyBugCapture.PNG)

**Comment by jimradford** [comment]
Looks like you are using a very old version (1.3). Can you attempt with a later version and report any problems if they still exist?
