### ISSUE TITLE
import layout

### ISSUE THREAD

**Issue by peklue** [jimradford/superputty#520]
Hello, a possibility to import a layout-file would be great. I run SuperPutty on a Windows Terminalserver and sometimes the settings get lost. Sure, this is a misbehavior of the Server. Anyway, it would be much easier to re-import the saved layout file, than to arrange all session Windows again. Thanks in advance!

**Comment by jimradford** [comment]
The Layout file(s) are located in Documents\SuperPuTTY by default. You should be able to copy those files to the same location on other hosts and be able to keep static layouts.

Closing this report, feel free to reopen if that above solution does not work for you.

**Comment by JosLuisDev** [comment]
Hi, I use super putty to server monitoring, I want to export and import a layout in the other host (another laptop) but it doesn't open anything It just shows me a message "loaded layout". I tried to copy the XML layout file in the other host in the path /Documents/SuperPuTTy/layouts
![image](https://user-images.githubusercontent.com/64123412/129926757-6eb7d1b1-d31f-4d5f-92ae-671cc4eac4f8.png)
