### ISSUE TITLE
Global "Extra PuTTY Arguments"

### ISSUE THREAD

**Issue by waukeerules** [jimradford/superputty#523]
I'd be interested in having global options created for "Extra PuTTY Arguments". This would allow me to use -auto_store_sshkey or -cmd (KiTTY commands) for every session I login. I know this feature exists for individual session settings.

**Comment by joeyhub** [comment]
I propose that you try editing the sessions XML instead. The format is fairly simple and you could also generate one from a template.

**Comment by waukeerules** [comment]
I've already done that. A global argument setting would allow all sessions to automatically store the SSH key even from the login bar. This would also work nicely for login scripts.

**Comment by jimradford** [comment]
I don't see why this cannot be easily implemented, I'll see if I can get it included in the next release.
