### ISSUE TITLE
CLI opened session opens in new window

### ISSUE THREAD

**Issue by geeksix** [jimradford/superputty#527]
Hi, 

I'm not sure if this is a bug, or just not a feature; Any time you launch a command (say with host information) to super putty via the command line, it opens a whole new window, rather than a new tab.

There are settings within SuperPutty which suggest SP will try and hold onto a single window, but in testing, it aways opens a new window.

Any thoughts?

**Comment by brpeterman** [comment]
I'm seeing the same thing. I can't get a second call to superputty.exe to ever load in a running instance.

Looks like Jim may already know about this:
https://github.com/jimradford/superputty/blob/master/SuperPutty/Program.cs#L46

**Comment by jimradford** [comment]
@geeksix what version of SuperPutty are you running? Can you see if the same behavior exists in the latest build available here: https://ci.appveyor.com/api/buildjobs/jf0esyf7wmaxpp77/artifacts/SuperPuttyInstaller/bin/Debug/SuperPuttySetup.msi

**Comment by bithexe** [comment]
@jimradford I had the same problem. Installed the MSI you linked above and now it works fine - thanks!

**Comment by jimradford** [comment]
@bithexe Thank you for testing it out and reporting its working.
