### ISSUE TITLE
Inconsistent history in send command toolbar

### ISSUE THREAD

**Issue by bluebird11** [jimradford/superputty#530]
After having sent a command, it is common to resend it (or to resend a command previously sent). To do so it is normal to press the up and down arrow and navigate through the history of the sent commands. Unfortunately this doesn't work consistently. When I press the up or down arrow I don't get the last command, but instead some random command from the history (I guess this happens when you have a lot of commands in the history). It would be great if this is fixed, since the command toolbar is one of the greatest features of SuperPutty! And writing the first letter and searching by it in history would also be quite useful. Saving command history on close would also be great.

**Comment by sisfs** [comment]
I couldn't agree more! the addition of bluebird's proposed features would make one of my favorite utilities, my absolute favorite utility!

**Comment by jimradford** [comment]
Thanks for the suggestion and report.

As of 1.4.0.7 the history order seems to be working correctly with up and down arrows going to previous or next entries in the history

Adding support for static command history is something we'll look into adding in the next release.

**Comment by jimradford** [comment]
Ok, this has been added to the code base. A few notes:

History can now be persistant between program restarts setting in Options->GUI
Number of days to save history can also be set in Options->GUI
CommandBar Behavior:
Pressing Up Arrow will scroll through the history starting with the most recently sent command. Down Arrow will scroll through backwards. This is similar to how bash does it in unix.

**Comment by jkldgoefgkljefogeg** [comment]
How to clear the history? Where is it stored?
