### ISSUE TITLE
windows10 slow down issue

### ISSUE THREAD

**Issue by arbiter9605** [jimradford/superputty#542]
Don't know if anyone else has had this issue with using, When i load Superputty up it has a weird effect of loading my computer down when loading like task manager, even has had side effect of causing winamp to freeze when i try to use the jump to file box. Spend the last 1-2 months trying to figure out what is causing it thought was fixed when just created a new account but issue came back when i loaded super putty back up. Not sure if its just some packed item that is the cause or what.

**Comment by jimradford** [comment]
What CPU/Memory usage is SuperPuTTY showing in Windows Task Manager?

**Comment by arbiter9605** [comment]
only uses .3% and 17MB of ram. 

i7 4770k 16gb ram.

**Comment by jimradford** [comment]
That is inline with what I would expect. There are no services or other processes running (besides Putty itself). Are any of those showing high memory or CPU usage?

**Comment by arbiter9605** [comment]
No none of them are.

**Comment by jimradford** [comment]
@arbiter9605 What are you showing in Task Manager to be using the most resources?

**Comment by arbiter9605** [comment]
usually its firefox, steam or chrome that uses most, never have slow down issues with them loaded.

**Comment by jimradford** [comment]
Ok, Maybe I am misunderstanding your issue with SuperPuTTY then.

Your initial report indicated your PC slowed down once you installed SuperPuTTY but nothing else you've shown has indicated SuperPuTTY is the cause. I do appreciate bug reports and I do want to do my best to resolve issues but I'm kind of at a loss on this one.

**Comment by arbiter9605** [comment]
Ok, issue is when i load superputty and program is loaded when i load say task manager, its slow and it hangs up, Same issue happens when i try to use jump to file in winamp. When i close superputty the issue stops instanty and the slow down stops. it effects the mouse as well.

**Comment by joeyhub** [comment]
I wonder if it could be related to the winevent issue. If you wait for the next version it might fix that. When you say slow do you mean as though the framerate/draw rate is very slow (often you see blank rectangular flat undrawn areas for a while but now all of windows looks like that with windows 10 so hard to tell)?

It would help if you can be very specific about how to reproduce your problem. Do you open superputty then do nothing or do you open any sessions, etc?

Sometimes performance issues can also be related to what you are doing in a session. For example, if you connect to cygwin on your own machine then run a command that uses a lot of CPU it might then cause things to go slow.

Windows doesn't always get CPU scheduling right and I find this can be a particular problem for the graphics threads in windows.

**Comment by jimradford** [comment]
@arbiter9605 try grabbing a copy of the installer from here: https://ci.appveyor.com/api/buildjobs/qtynviv6pkn6arw7/artifacts/SuperPuttyInstaller/bin/Debug/SuperPuttySetup.msi This contains the fixes @joeyhub  mentioned in #538 Let us know if that is any improvement. Thanks for the Video, that clearly demonstrates the issue you mention.

**Comment by arbiter9605** [comment]
Much improved, don't seem any slowness in task manager anymore least initially. Let it run for a while see if anything happens over time.

**Comment by jimradford** [comment]
@arbiter9605 Thanks for testing. I'll consider this issue to be closed. We will shortly publish an official 1.0.4.7 release so everyone can benefit from @joeyhub 's improvements. If you run into any more issues please feel free to reopen this issue and add any pertinent information you are able.
