### ISSUE TITLE
Option to not cache password / send in clear text to PuTTY via command line

### ISSUE THREAD

**Issue by JeffWDH** [jimradford/superputty#546]
Hello,

It would be nice to have an option to have SuperPuTTY not send passwords to PuTTY via the command line. Expected behavior with this option would be for PuTTY to always ask for a password when duplicating tabs or opening File Transfer windows.

The reason for this request is because the password is visible simply by running this (or other similar) PowerShell command: Get-WmiObject Win32_Process | select name, commandline

Steps to reproduce:

1) Right click on a host, select File Transfer
2) Enter password
3) Double click on a host to start a SSH session, it doesn't ask for a password
4) Check Get-WmiObject Win32_Process | select name, commandline and see your password in plain text.

Thanks!

**Comment by jimradford** [comment]
@JeffWDH Thanks, I 100% agree. I believe this can be a pretty big security risk especially if SuperPuTTY is being used in a multi-user environment. I don't personally want SuperPuTTY having anything to do with passwords - its in-congruent to be using "secure shell" then doing something silly like exposing passwords.

The solution is to implement the "-i key    private key file for authentication" command line option for pscp, This would not restrict people from using a password on the commandline but would give a secure option as an alternative.

**Comment by jimradford** [comment]
Ok, by default the -pw argument cannot be sent to putty now. This can be overridden in tools->options->GUI to allow this unsafe behavior.
