### ISSUE TITLE
Run Script Issues

### ISSUE THREAD

**Issue by waukeerules** [jimradford/superputty#549]
There's an issue I noticed today with the new run script feature. Depending on how large your script is, you could potentially out run the buffer and corrupt your configuration file. I tested this by creating a large configuration file and sending it to a COM port. The best way to resolve this issue would be to send lines one by one instead of all at once. 

Also, I don't think you should allow the tool to send scripts to all windows unless specifically requested by the user. I could easily send a large amount of configurations to all my open sessions by accident and potentially knock a device offline by a simple mistake. 

Let me know your thoughts.

**Comment by jimradford** [comment]
right now the script is sent line by line albeit very quickly, other than that the behavior is exactly the same as the command bar in features and functionality. I am not sure I want to have it too different from the way the command bar operates as that would likely create some confusion. We could possibly add a configurable delay between lines if that might solve your issue.

**Comment by jimradford** [comment]
@waukeerules About Ready with SPSL which should alleviate the issue you're having with buffering overruns sending directly to a COM port. Take a look at Issue #558 It might end up being a good solution for you.
