### ISSUE TITLE
file transfer is not working

### ISSUE THREAD

**Issue by vp70** [jimradford/superputty#556]
Remote configuration for file transfer is defaulting to /home/username
This is not the case for me. I get error "System error while loading directory: Object reference is not set". Because i dont have that directory. Can you add logic that defaults to /home/ if /home/username/ does not exist. With out this fix File Transfer is not usable.

P.S.
I found there is a option to set starting directory in GUI Options dialog for File Transfer, but its not picking up changes even if I set to /home/

Thanks in advance.
-VP70

**Comment by vp70** [comment]
I found there is a option to set starting directory for in GUI option dialog for File Transfer, but its not picking up changes even if I set to /home/

**Comment by jimradford** [comment]
are you logging in as root or as a different username other than root?

**Comment by vp70** [comment]
Different user. I don't have access to root

**Comment by vp70** [comment]
![image](https://cloud.githubusercontent.com/assets/15113532/10521597/b67702d2-733e-11e5-9b33-b97b9bad4739.png)

**Comment by jimradford** [comment]
@vp70 Can you open the log viewer and re-attempt to connect to transfer a file. I'd like to track down the cause of the null object reference.

**Comment by vp70** [comment]
![image](https://cloud.githubusercontent.com/assets/15113532/10522214/0458034a-7342-11e5-99e3-e8feedf08b77.png)

**Comment by vp70** [comment]
Here is my File Transfer Options that not being picked up.

![image](https://cloud.githubusercontent.com/assets/15113532/10522302/829eac36-7342-11e5-8bf5-b54ab236cb02.png)

**Comment by jimradford** [comment]
@vp70 When you change "Home Directory Prefix" to "/home/user/" does it work as expected?

**Comment by vp70** [comment]
That worked.
I am confused on what is difference between Home directory Prefix and Remote Directory Prefix?

Thanks for making it work!

**Comment by jimradford** [comment]
"Home Directory Prefix" is the default path pre-pended to the username for remote hosts. For example: if your home directory path is "/home/user/vp70", we only know your username, so that allows you to tell SuperPuTTY where to start.

"Root Directory Prefix" is only used when the username is "root", most times it should be simply "/" since root's home directory is generally "/root" on most *nix systems.

Nonetheless, I will add better error checking to prevent the null object reference message.

**Comment by vp70** [comment]
thanks

**Comment by nitin-pai** [comment]
Can you make this editable as in WinSCP. I do not see much usage of this with fixed paths.
