### ISSUE TITLE
unhandled error when run on windows 10 pro 64bits.

### ISSUE THREAD

**Issue by rbadillarx** [jimradford/superputty#557]
hi people:
Recently I moved from Windows 7 Ultimate 32bits to Windows 10 Pro 64bits over MBP (Mac Book Pro; via boot camp). After install superputty from msi files I got this error..
![2015-10-15 09_46_25-unhandled error](https://cloud.githubusercontent.com/assets/15144695/10519554/7b4187de-7323-11e5-8202-0d7dba40c889.png)
![2015-10-15 09_46_25-unhandled error](https://cloud.githubusercontent.com/assets/15144695/10519567/85bb0154-7323-11e5-98fc-0ab5fce02627.png)

any idea what's wrong???

**Comment by jimradford** [comment]
It appears its something to do with a SSL connection, Maybe to do with the automatic update checker

In the Folder you installed SuperPuTTY there should be a file named SuperPutty.exe.config, open that file in a text editor and search for these lines:

<setting name="AutoUpdateCheck" serializeAs="String">
        <value>True</value>
      </setting>

Change the True to False, Save the file

Try to re-open SuperPuTTY and see if the error still persists. Report back your results and we'll try to come up with a good fix.

**Comment by jimradford** [comment]
You can download and test a version from here: https://ci.appveyor.com/api/buildjobs/cffc34k4rsqj0dko/artifacts/SuperPuttyInstaller/bin/Debug/SuperPuttySetup.msi that might possibly fix the issue you are experiencing.

**Comment by rbadillarx** [comment]
Hi Jim:
Thanks by your help and software.
I make both things; change the 
      <setting name="AutoUpdateCheck" serializeAs="String">
        <value>True</value>
      </setting>
to
      <setting name="AutoUpdateCheck" serializeAs="String">
        <value>False</value>
      </setting>
Launch version SuperPuTTY-1.4.0.7 got this error
![2015-10-15 10_58_22-unhandled error](https://cloud.githubusercontent.com/assets/15144695/10521314/65fabfc2-732c-11e5-96ea-eb80cba8c8b3.png)

After that, download the other installer; __uninstall the older superputty__, then install and lauch and works like a charm!!! I look the help--> about  and says version 1.4.0.7.

Thanks a lot!

**Comment by jimradford** [comment]
Issue appears to be caused internally by some component of the .NET framework related to SSL certificates possible, Added error checking in calling method to prevent exception. This does not fix the underlying issue and in some circumstances the update checks will simply not occur if this issue exists on the host system.

**Comment by jimradford** [comment]
@rbadillarx can you open the log viewer: View Menu -> Log Viewer (if its not already open)
Then check for updates: Help Menu -> Check For Updates and report back if it was successful or failed?

Thanks!

**Comment by rbadillarx** [comment]
Hi Jim:
It failed here's the window output:
2015-10-15 11:24:43,070 INFO      Log4netLogViewer - Viewer Ready (1.2.13)
2015-10-15 11:24:43,157 INFO      ApplicationPanel - MoveWindow [OnResize       ImportedFromPuTTY/arc04] w= 806, h= 388, visible=True, success=True
2015-10-15 11:24:43,171 DEBUG           SuperPuTTY - STATUS: Showing Log Viewer
2015-10-15 11:24:47,933 INFO         frmSuperPutty - Checking for application update
2015-10-15 11:24:53,204 ERROR              Program - CurrentDomain_UnhandledException: IsTerminating=True, ex=System.Net.WebException: Se ha terminado la conexión: No se puede establecer una relación de confianza para el canal seguro SSL/TLS. ---> System.Security.Authentication.AuthenticationException: El certificado remoto no es válido según el procedimiento de validación.
   en System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   en System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   en System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   en SuperPutty.httpRequest.RespCallback(IAsyncResult ar)
   en System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   en System.Threading.ExecutionContext.runTryCode(Object userData)
   en System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Net.ContextAwareResult.Complete(IntPtr userToken)
   en System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   en System.Net.HttpWebRequest.SetResponse(Exception E)
   en System.Net.ConnectStream.ProcessWriteCallDone(ConnectionReturnResult returnResult)
   en System.Net.ConnectStream.CallDone(ConnectionReturnResult returnResult)
   en System.Net.ConnectStream.IOError(Exception exception, Boolean willThrow)
   en System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   en System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   en System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   en System.Net.TlsStream.ResumeIOWorker(Object result)
   en System.Net.TlsStream.WakeupPendingIO(IAsyncResult ar)
   en System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   en System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   en System.Net.Security.SslState.FinishHandshake(Exception e, AsyncProtocolRequest asyncRequest)
   en System.Net.Security.SslState.ReadFrameCallback(AsyncProtocolRequest asyncRequest)
   en System.Net.FixedSizeReader.CheckCompletionBeforeNextRead(Int32 bytes)
   en System.Net.FixedSizeReader.ReadCallback(IAsyncResult transportResult)
   en System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   en System.Threading.ExecutionContext.runTryCode(Object userData)
   en System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   en System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   en System.Net.ContextAwareResult.Complete(IntPtr userToken)
   en System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   en System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   en System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
2015-10-15 11:24:53,205 DEBUG        frmSuperPutty - [593708] Activated
2015-10-15 11:24:53,321 INFO      ApplicationPanel - [265916] ReFocusPuTTY - puttyTab=10.150.0.84 - PuTTY, caller=SHELLHOOK, result=True
2015-10-15 11:25:13,546 DEBUG        frmSuperPutty - [593708] Activated
2015-10-15 11:25:13,629 INFO      ApplicationPanel - [265916] ReFocusPuTTY - puttyTab=10.150.0.84 - PuTTY, caller=SHELLHOOK, result=True
2015-10-15 11:25:14,922 DEBUG        frmSuperPutty - [593708] Activated
