### ISSUE TITLE
Session folder name in the tab title.

### ISSUE THREAD

**Issue by vipconsult** [jimradford/superputty#566]
Hi 

do you think you could add an option to add the folder name on tab name ?

many of the session names i use are the same and by adding the folder name in the tab will help me identify which session I am working on.

I have attched a draft of my idea. 

if the folder name or the session name  is too long or there are too many tabs open it can only show few letters as this would be enough to know which tab belongs to which session.

![tabsnaming](https://cloud.githubusercontent.com/assets/8903888/10868324/0989ce16-8094-11e5-908e-6ee1cbaaabec.jpg)

**Comment by jimradford** [comment]
We'll see about getting something added to help you out with this. I am thinking a user definable string with expandable variables to give everyone flexibility to have the tab naming the way they prefer.
