### ISSUE TITLE
[Question] Auto execute a command after logged successfully.

### ISSUE THREAD

**Issue by msmosso** [jimradford/superputty#574]
Hi folks,

I made the script above

```
#!/bin/spsl
SLEEP 3500
SENDLINE PS1='\e[0;36m(\e[1;36m\u\e[0;36m@\e[1;36m\h\e[0;36m) \e[1;36m\$\e[0m '
SENDLINE clear
```

But I would like to have it executed right after I log in. The actual result is that it takes 3500 miliseconds and if I err the password or delay it the command also auto executes.

Is it possible?
Thanks in advance.

Cheers!

**Comment by jimradford** [comment]
Hi Matteus,

Currently there is no way to support waiting for or knowing when a login is successful, You are using the best supported method which is to use a SLEEP command to delay further execution.

**Comment by mcarbonneaux** [comment]
while be interesting to integrate expect like library in spsl language !
- http://blog.iwanek.eu/expect-net/
- https://github.com/CBonnell/dotnetexpect
are exemple of expect library for c#...
