### ISSUE TITLE
Extend on Commands function and contributors mention.

### ISSUE THREAD

**Issue by george-vieira** [jimradford/superputty#578]
I've created a new function similar to linux cssh command where opening multiple windows and have keys sent to all windows (imagining opening VIM on multiple machines and editing all at the same time).
I've got this working but lacking all the keys properly due to windows funny way to handle key capturing. But something like this would benefit me more than the "Commands" option available

Also mentioned in google code some time back (Issue #318), would be nice to add acknowledgements to contributors like myself for a number of patches that have made it through.

**Comment by george-vieira** [comment]
Can you not simply add the patch for the 2nd part of the question. attached the original patch from goolecode

[DevelopedBy.patch.txt](https://github.com/jimradford/superputty/files/142109/DevelopedBy.patch.txt)

**Comment by jimradford** [comment]
Hi George, 
Little stale -- sorry! I'm busy with other projects, glad to revisit this if you submit it in a pull request. I have added a link in the acknowledgements tab to code contributors.
