### ISSUE TITLE
Detection of disconnected tabs

### ISSUE THREAD

**Issue by janpio** [jimradford/superputty#579]
I think this is still needed, at least I couldn't distinguish the dead from the alive tabs :/

https://code.google.com/p/superputty/issues/detail?id=466&q=disconnected

> It would be helpful to detect disconnected tabs and display them with alternate icon/color. Also for such tabs context menu should be stripped.
> And most usable is to restart session for such tabs by just pressing Enter (like in putty-nd)
> 
> Please consider this patches for implementation:
> https://github.com/sepich/superputty/commit/d7abc32d70f37979eaef308a05f6510fab2fc8c8
> https://github.com/sepich/superputty/commit/f75d61385fc552d70ad7a6cd27d27dee3283514d

**Comment by crisistotal2014** [comment]
Hi!
It's possible to add to this improvement a little icon on tab to show tab status (red when there is data movement, green when there is, etc.)? This is a feature that SecureCRT has and is usefull.
Thanks!
