### ISSUE TITLE
SuperPutty not starting on Windows 7

### ISSUE THREAD

**Issue by MetalCar** [jimradford/superputty#598]
I have a problem starting superputty. When i start it, it doesn't show up the superputty window. When I have a look in the task manager, i can see that there is a superputty task in there. Hanging at 15MB memory usage. I killed this task and restart superputty as administrator.....it seems to work now. 

But i know that i can superputty run not as an administrator. Is this a bug or do you wanted that superputty do that?

**Comment by roltd** [comment]
May be disable the second display and after this run the SuperPuTTY.

**Comment by MetalCar** [comment]
I disabled the second display and SuperPutty also won't start.
Additional info:
I see that in my taskbar where my superputty quickstart icon is, the icon is highlighted. Then the task hang up and the icon isn't highlighted anymore.

**Comment by infectormp** [comment]
not have any problem on windows 7/8/10 x64

**Comment by ringnutz** [comment]
This seems to affect users who are not administrators. 

Admin users work fine.

CPU usage is around 14% and memory usage stays between 18 and 20k during this time.

**Comment by MetalCar** [comment]
i tried to find the bug myself. i compiled the Solution as Debug and as Release. debug was hanging and release started immediatly
