### ISSUE TITLE
Feature Request: Don't restore sessions on restart

### ISSUE THREAD

**Issue by willhughes** [jimradford/superputty#630]
Per the title, when I open SuperPuTTY I would like it to NOT remember any sessions - it can take a long long time to open up all the sessions I used to have open and I often don't want those same sessions anymore. 

Apologies if this is a duplicate, I did search some obvious keywords in the issues, and looked over the options but couldn't see anything likely either.

**Comment by waukeerules** [comment]
This might be happening because your had a bunch of sessions open and saved the layout. I haven't ever tried that, but close all your sessions and save the layout. When you open super putty the next time it should restore the layout without the previous sessions open.

**Comment by willhughes** [comment]
@waukeerules  Ah, not quite. But the think about Layouts is what I needed. Hadn't noticed that feature before. 

For anyone else having SuperPuTTY remember sessions for them when they don't want it to: 

In Tools -> Options -> General, changing 'Default Layout' to an empty selection ensures it doesn't load any previously open sessions.
