### ISSUE TITLE
Pressing [Alt Gr] key (right Alt-key on german keyboard) clears Command input

### ISSUE THREAD

**Issue by Skeeve** [jimradford/superputty#642]
When entering a command which requires any character accessible with by pressing the  [Alt Gr] key, like | @ \ ~, the command input gets cleared.

**Comment by nexosone** [comment]
Hi Skeeve, could it be a local problem?
I tried it on several unix machines and there don't exist that problem.
------
Ich als Besitzer einer deutschen Tastatur besitze das Problem nicht. ;-)
getestet auf Redhat, SunOS, Debian.

Client: Windows 7 x86 

Supper putty Version: 1.4.0.8

**Comment by Skeeve** [comment]
SuperPuTTY 1.4.0.8
Windows 7 Enterprise SP1

When not connected to any host, Trying to enter a pipe or @ doesn't do anything in the command input field. The character seems to be ignored.

When connected to Linux 2.6.32-431.e16.x86_64 #1 (?) Pressing Alt-GR key because I require an @ in the command input field erases that field. Entering the @ in the shell window or pasting it into the command input field yields no problem.

No clue what else I could do to give more help.

There is also no issue with the ALt-Gr key in the host, login or password input field

**Comment by Skeeve** [comment]
New observation: When enter any character requiring me to press Alt-Gr into the command input field, not only the input field gets erased, but the character is copied into every open shell.

Example.
I want to type "Skeeve@Home" into the command input field.
I type "Skeeve" -> It appears in the field.
I press Alt-Gr -> The field get emptied
I continue with the "@" sign -> The field remains empty but the shell now has an @
I type "home" -> It appears in the field

**Comment by aruehl** [comment]
Same behavior. Pressing AltGr cleares the Command field and pressing an additional key prints the character into the putty window.

**Comment by irstmon** [comment]
Bump
