### ISSUE TITLE
Restart all sessions with one click

### ISSUE THREAD

**Issue by frankenstein91** [jimradford/superputty#656]
I would like to have the possibilitie to restart all sessions in my superputty with one command.
It's because of a bad network and make it easy for me to restart all sessions very fast.

![image](https://cloud.githubusercontent.com/assets/2527348/24787091/8cd7a612-1b66-11e7-94c7-a337d8c95e61.png)

- [ ] Add a new menu item
- [ ] make it work as close all, but restart the sessions

**Comment by sohagan857** [comment]
This is already supported - save all your sessions, or whatever sessions you need to quickly restart, as a pre-defined layout, lets say "all". Whenever you need to restart these sessions, simply click the "all" line on the layouts menu. This will close all sessions, and restart any session defined in the "all" layout. All it requires is a double click.

**Comment by frankenstein91** [comment]
Hello sohagan 
This is not the same function. If you restart a session you are able to look and copy from old in/output. Your idea will reopen the sessions, this will discard all old in/output. 
Thanks in advance

**Comment by thymeore** [comment]
I have the same problem as @frankenstein91. During work, I need sometimes the old input/output of the crashed sessions and also because of the bad network I have to restart all sessions (usually ~ 5-10) a few times a day.

**Comment by sohagan857** [comment]
Ah - nice one Frankenstein - that would indeed be useful. Didn't consider in/output, I just log session output, but that would be a neat feature. My mistake, hope it gets tracked.

**Comment by dinoopp** [comment]
+1

**Comment by magarvo** [comment]
+1

**Comment by hawkeye20** [comment]
+1

**Comment by mstv** [comment]
I would appreciate this function very much, especially with a hotkey.

**Comment by vitali-kurylovich** [comment]
+1

**Comment by frankenstein91** [comment]
I have already forgotten about the wish. After longer nothing has happened, I have changed the product.

Does anyone want to take over this request or do we want to close it?

**Comment by dinoopp** [comment]
Sorry I switched to mobaeXterm

**Comment by jimradford** [comment]
Unfortunately when you restart a putty session it (putty) clears the screen of old information. This feature would have to be implemented in putty itself, not in SuperPuTTY.
