### ISSUE TITLE
SuperPutty 1.4.0.8 crashes on launch "SuperPutty has stopped working"

### ISSUE THREAD

**Issue by catalinciubotariu** [jimradford/superputty#665]
Hi Jim,

Many thanks for maintaing SuperPutty. First time when I have to use it on Windows 2008 R2 and it's not working, please see below the details:

Description:
  Stopped working

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	superputty.exe
  Problem Signature 02:	1.4.0.8
  Problem Signature 03:	562e9c7e
  Problem Signature 04:	mscorlib
  Problem Signature 05:	2.0.0.0
  Problem Signature 06:	55f8e01b
  Problem Signature 07:	f9b
  Problem Signature 08:	14e
  Problem Signature 09:	System.IO.FileNotFoundException
  OS Version:	6.1.7601.2.1.0.18.10
  Locale ID:	6153

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Thanks for your feedback!

**Comment by george-vieira** [comment]
System.IO.FileNotFoundException
Something is missing from your installation. It's a dirty error and not handled properly.

this is a sample DIR of my installed copy. make sure you have something similar
11/04/2016  04:23 PM    <DIR>          .
11/04/2016  04:23 PM    <DIR>          ..
11/02/2016  04:38 PM             1,143 License.txt
11/04/2016  04:23 PM           311,296 log4net.dll
11/02/2016  04:38 PM               638 README.txt
11/02/2016  04:38 PM            19,284 ReleaseNotes.txt
16/07/2015  03:04 PM           529,118 SuperPutty-cssh.zip
11/04/2016  04:21 PM         1,055,232 SuperPutty.exe
11/04/2016  04:22 PM             8,917 SuperPutty.exe.config
03/05/2015  07:38 PM           755,200 SuperPutty.pdb
03/05/2015  07:43 PM            11,608 SuperPutty.vshost.exe
23/05/2013  08:29 PM             8,466 SuperPutty.vshost.exe.config
17/03/2010  10:39 PM               490 SuperPutty.vshost.exe.manifest
28/10/2013  09:25 PM    <DIR>          themes
11/04/2016  04:22 PM           364,544 WeifenLuo.WinFormsUI.Docking.dll
              12 File(s)      3,065,936 bytes
               4 Dir(s)  392,828,010,496 bytes free
