### ISSUE TITLE
Home prefix option doesn't work in some scenarios

### ISSUE THREAD

**Issue by george-vieira** [jimradford/superputty#669]
version 1.4.0.8

This is an assumption to use /home/$username and doesn't work in all scenarios when using SCP function.

example is when the root user on some systems is called admin.
so admins home directory is /root but SP assumes /home/admin and that's bad.

I can't even create a session with SCP which would have been good to have with a 'login to path' option as to bypass assuming the user wants to always go to $HOME. This way a session of SCP can jump directly to a website path if the user wants it that way.

**Comment by zoff99** [comment]
i have the same issue, can't use scp because homedir is hardcoded.
please help

**Comment by zoff99** [comment]
just removing the homedir argument works for me.

**Comment by george-vieira** [comment]
what homedir argument? anyway, don't care for scp anymore nor this project who doesn't appreciate contributors.

**Comment by jimradford** [comment]
@george-vieira 

The homedir setting in tools->options (F2)

I do apologize if you did not receive some sort of hand holding you expect. This project is open source, which means I and many others have spent hundreds of hours making it work for our purposes. As a side benefit others can use it for their own purposes, even modify it if they so choose, and if they want contribute changes back. There is no requirement or expectations that anyone does however. 

What exactly do you feel we did not do to show appreciation for contributors?
Jim

**Comment by george-vieira** [comment]
Closed #578
