### ISSUE TITLE
Improve documentation for developers not using Visual Studio, e.g. SharpDevelop

### ISSUE THREAD

**Issue by larsen0815** [jimradford/superputty#671]
The wiki page doesn't mention what to install when not using Visual Studio. I found out that I need 
the "Microsoft Windows SDK for Windows 7 and .NET Framework 3.5 SP1". Otherwise, running the project would result in a '"resgen.exe"  not found' error.

It would be good to have the link https://www.microsoft.com/en-us/download/details.aspx?id=3138 for the SDK on https://github.com/jimradford/superputty/wiki/Developers

**Comment by t0r0X** [comment]
@larsen0815 I've added your suggestion to the Developers-Page, as it's a Wiki page. If your're satisfied with the addition, you might want to close this ticket :-)

**Comment by larsen0815** [comment]
thx!
