### ISSUE TITLE
Keep alive

### ISSUE THREAD

**Issue by DzenDyn** [jimradford/superputty#672]
Hello, that's feature request for keep alive function. I have troubles with many error messages, when cisco disconnect me by timeout.

**Comment by ccie5022** [comment]
I second this. I have seen in another Terminal program, it can send a key stroke every X seconds. Not sure if this would be a Putty or Superputty function.

**Comment by waukeerules** [comment]
I use KiTTY instead of PuTTY which has options for keeping a session alive. 
http://kitty.9bis.net

**Comment by jimradford** [comment]
This would be a function of putty itself, I suppose something could be hacked in, but probably @waukeerules suggestion is the better option.
