### ISSUE TITLE
[SOLVED] Disable Auto Check for Updates + Full Silent Install Details

### ISSUE THREAD

**Issue by EricSP2** [jimradford/superputty#675]
I've created a silent deployment for my organization.

Great tool!

However one nagging issues seems to be the "Check For Updates"

in **%ProgramFiles(x86)%\SuperPuTTY\SuperPutty.exe.config** I change the parameter below:

`<setting name="AutoUpdateCheck" serializeAs="String">   
<value>True</value> 
</setting>
`

I change it to **false** and it does not seem to make any difference? Also in **%appdata%** I don't see any relevant config files.

Where should I be looking? Is this project still alive?

**Comment by dbz78** [comment]
Hello,
I've been looking for the same information in **SuperPutty 1.4.0.8**, and spent some time tweaking **SuperPutty.exe.config** file with no result, as you did.  Another parameter change did not work either:
`<setting name="ExitConfirmation" serializeAs="String"><value>False</value></setting>`

Then reading thoroughly the documentation again ( [https://github.com/jimradford/superputty/wiki/Documentation#configuration-files](url) ), I discovered that settings were in fact defined in **%USERPROFILE%\SuperPuTTY.settings** and that it is adviced to **NOT** modify it directly but through GUI, typing F2 to pop up the "Options" window. Of course, **with caution**, one can modify it outside SuperPutty.

Eventually I have not idea what **SuperPutty.exe.config** is worth for. Documentation states "_For **advanced logging** settings and **application runtime** settings there is a file called SuperPutty.exe.config in the application directory that allows runtime configuration of the SuperPuTTY Application._". But since behaviour does not change as expected when it is modified in the _**<userSettings / SuperPutty.Properties.Settings>**_ section, this file is a mystery to me. Maybe is it dead code?

In your case, for silent deployment, you should then copy a preset version of **SuperPuTTY.settings** in each and every **%USERPROFILE%** target, though it may be no so easy to do and not very convenient.
Thanks to make us know if and how you eventually did it, or not.

Hope this helps,
DBZ78

**Comment by EricSP2** [comment]
Great discovery, I completely missed that file in the **%USERPROFILE%** or maybe overlooked it when I did a system-wide search for it.

So essentially the settings file is generated by a hardcoded bit for SuperPutty and cannot be changed prior to installation.

After reading your reply I changed the files to **.bak** of it and restarted superputty, essentially all settings are lost as this is the primary preference for the user. For existing user I need a script that loops through all the profiles under **\users** and then do some kind of grep-like result and replace.

Shouldn't be too hard.

Although this effort is in vain for a silent deployment as the setting file for the user profile doesn't seem to be generated from a template file. So the mod script would have to run and loop everytime it's generated.

Essentially at this point I've given up further research into the tool as it's a limited distribution within my organization and is very low priority.

**Comment by EricSP2** [comment]
Perhaps pushing the settings file to the **default** user profile directory in **\users** could fix the issue though. remains to be seen.

**Comment by EricSP2** [comment]
I figured out 3b partially...

```
(Get-Content SuperPuTTY.settings) | ForEach-Object { $_ -replace "True</AutoUpdateCheck>", "False</AutoUpdateCheck>" } | Set-Content SuperPuTTY.settings
```
make a ps1 powershell script and call it from command prompt (if running from SCCM for example)

So the command would look like this from a batch:

"%WinDir%\System32\WindowsPowerShell\v1.0\PowerShell.exe" Set-ExecutionPolicy Unrestricted

"%WinDir%\System32\WindowsPowerShell\v1.0\PowerShell.exe" (Get-Content SuperPuTTY.settings) | ForEach-Object { $_ -replace "True</AutoUpdateCheck>", "False</AutoUpdateCheck>" } | Set-Content SuperPuTTY.settings

"%WinDir%\System32\WindowsPowerShell\v1.0\PowerShell.exe" Set-ExecutionPolicy Restricted

Now ontop of that  script you need a loop the browses through the **\users** directory...

**Comment by EricSP2** [comment]
Settings file example:

```
<?xml version="1.0" encoding="utf-8"?>
<Settings>
  <AutoUpdateCheck>False</AutoUpdateCheck>
  <SessionsTreeFont>Segoe UI, 9pt</SessionsTreeFont>
  <ShowDocumentIcons>False</ShowDocumentIcons>
  <TabTextBehavior>Static</TabTextBehavior>
  <PscpHomePrefix>/home/</PscpHomePrefix>
  <WindowState>Normal</WindowState>
  <SessionsSearchMode>CaseSensitive</SessionsSearchMode>
  <PuttyPanelShowNewSessionMenu>True</PuttyPanelShowNewSessionMenu>
  <DefaultLayoutName>&lt;Auto Restore&gt;</DefaultLayoutName>
  <MultipleTabCloseConfirmation>False</MultipleTabCloseConfirmation>
  <MinttyExe>
  </MinttyExe>
  <DockingRestrictFloatingWindows>False</DockingRestrictFloatingWindows>
  <CommandBarHistory>&lt;?xml version="1.0" encoding="utf-16"?&gt;
&lt;ArrayOfHistoryEntry xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" /&gt;</CommandBarHistory>
  <ShowToolBarCommands>True</ShowToolBarCommands>
  <Action_Options_Shortcut>F2</Action_Options_Shortcut>
  <PscpExe>\Program Files\PuTTY\pscp.exe</PscpExe>
  <ExpandSessionsTreeOnStartup>False</ExpandSessionsTreeOnStartup>
  <TabSwitcher>SuperPutty.Utils.VisualOrderTabSwitchStrategy</TabSwitcher>
  <Action_OpenScriptEditor_Shortcut>None</Action_OpenScriptEditor_Shortcut>
  <SendCommandsToVisibleOnly>False</SendCommandsToVisibleOnly>
  <AlwaysOnTop>False</AlwaysOnTop>
  <Opacity>1</Opacity>
  <ShowToolBarConnections>True</ShowToolBarConnections>
  <SettingsFolder></SettingsFolder>
  <Action_FocusActiveSession_Shortcut>None</Action_FocusActiveSession_Shortcut>
  <RestoreWindowLocation>True</RestoreWindowLocation>
  <PersistCommandBarHistory>True</PersistCommandBarHistory>
  <EnableKeyboadShortcuts>True</EnableKeyboadShortcuts>
  <PuttyExe>\Program Files\PuTTY\putty.exe</PuttyExe>
  <SessionsShowSearch>True</SessionsShowSearch>
  <Action_CloseTab_Shortcut>None</Action_CloseTab_Shortcut>
  <EnableControlTabSwitching>True</EnableControlTabSwitching>
  <ApplicationVersion>
  </ApplicationVersion>
  <Action_RenameTab_Shortcut>None</Action_RenameTab_Shortcut>
  <ExitConfirmation>True</ExitConfirmation>
  <Action_FullScreen_Shortcut>F11</Action_FullScreen_Shortcut>
  <Action_GotoConnectionBar_Shortcut>None</Action_GotoConnectionBar_Shortcut>
  <ShowStatusBar>True</ShowStatusBar>
  <SaveCommandHistoryDays>7</SaveCommandHistoryDays>
  <SingleInstanceMode>False</SingleInstanceMode>
  <WindowPosition>208, 208, 1024, 749</WindowPosition>
  <RestrictContentToDocumentTabs>False</RestrictContentToDocumentTabs>
  <Action_SwitchSession_Shortcut>None</Action_SwitchSession_Shortcut>
  <PscpRootHomePrefix>/</PscpRootHomePrefix>
  <Action_DuplicateSession_Shortcut>None</Action_DuplicateSession_Shortcut>
  <ShowMenuBar>True</ShowMenuBar>
  <Action_PrevTab_Shortcut>None</Action_PrevTab_Shortcut>
  <AllowPlainTextPuttyPasswordArg>False</AllowPlainTextPuttyPasswordArg>
  <Action_OpenSession_Shortcut>None</Action_OpenSession_Shortcut>
  <MinimizeToTray>False</MinimizeToTray>
  <WindowActivator>SuperPutty.Utils.KeyEventWindowActivator</WindowActivator>
  <QuickSelectorCaseSensitiveSearch>False</QuickSelectorCaseSensitiveSearch>
  <SessionsTreeShowLines>False</SessionsTreeShowLines>
  <Action_NextTab_Shortcut>None</Action_NextTab_Shortcut>
  <Action_GotoCommandBar_Shortcut>None</Action_GotoCommandBar_Shortcut>
</Settings>
```

Notes:

```
<PscpExe>\Program Files\PuTTY\pscp.exe</PscpExe>
```

and

```
<PuttyExe>\Program Files\PuTTY\putty.exe</PuttyExe>
```
I left out the C:\ for a \ instead to make it OSDrive agnostic.

And for...

```
<SettingsFolder></SettingsFolder>
```

This was left blank and the app will send it to the system's default **%userprofile%\Document\SuperPutty\filename.settings**, do note that if you have OneDrive installed I saw a weird bug where my Documents directory default was set to **OneDrive\Documents\...**

**Comment by EricSP2** [comment]
So this is the final solution, this will install the software and **Superputty.settings** with AutoUpdate disabled on existing and future users and modify the parameters if it exists.

Note you need to use the **Superputty.settings** from above with the script below in on directory.

```
@ECHO OFF

REM Install Putty & SuperPutty silently, no restart
REM SRC https://github.com/jimradford/superputty/releases/download/1.4.0.8/SuperPuttySetup-v1.4.0.8.msi
REM SRC https://the.earth.li/~sgtatham/putty/latest/w64/putty-64bit-0.70-installer.msi

MSIEXEC /I "putty-64bit-0.70-installer.msi" /QN /NORESTART
MSIEXEC /I "SuperPuttySetup-v1.4.0.8.msi" /QN /NORESTART

REM If the "SuperPutty.settings" file doesn't exist in the user directory, copy it inside.

DIR \Users /A:D-H-S /B > DIR.txt

FOR /f "delims=" %%G in (DIR.txt) DO (
	
	IF NOT EXIST "\USERS\%%G\SuperPutty.settings" (
		COPY /Y "SuperPutty.settings" "\USERS\%%G\".
	) 
)
DEL /F /Q DIR.txt

REM Copy the file "SuperPutty.settings" to the default user profile so when new user is created.
COPY /Y "SuperPutty.settings" "\USERS\Default\".

REM If the file "SuperPutty.settings" exist edit the auto-update section with powershell
"%WinDir%\System32\WindowsPowerShell\v1.0\PowerShell.exe" Set-ExecutionPolicy Unrestricted
"%WinDir%\System32\WindowsPowerShell\v1.0\PowerShell.exe" .\replace.ps1
"%WinDir%\System32\WindowsPowerShell\v1.0\PowerShell.exe" Set-ExecutionPolicy Restricted

EXIT /B
```
The code for the replace.ps1 file is the following:

```
$configFiles = Get-ChildItem . SuperPuTTY.settings -rec
foreach ($file in $configFiles)
{
    (Get-Content $file.PSPath) |
    Foreach-Object { $_ -replace "True</AutoUpdateCheck>", "False</AutoUpdateCheck>" } |
    Set-Content $file.PSPath
}
```

So put the **replace.bat, replace.ps1, SuperPutty.settings, SuperPuttySetup-v1.4.0.8.msi & putty-64bit-0.70-installer.msi** in one directory and run the setup starting with replace.bat

Voila! Nob's your uncle!

**Comment by EricSP2** [comment]
Uninstallation process:

```
MSIEXEC /X "putty-64bit-0.70-installer.msi" /QN /NORESTART
MSIEXEC /X "SuperPuttySetup-v1.4.0.8.msi" /QN /NORESTART
```

**Comment by EricSP2** [comment]
Remove the .txt filename

[replace.bat.txt](https://github.com/jimradford/superputty/files/1594091/replace.bat.txt)
[replace.ps1.txt](https://github.com/jimradford/superputty/files/1594092/replace.ps1.txt)
[SuperPuTTY.settings.txt](https://github.com/jimradford/superputty/files/1594093/SuperPuTTY.settings.txt)

**Comment by EricSP2** [comment]
I also confirm that copying the file to \users\default\SuperPutty.settings makes it so all future users will get the default parameters.

Also if you've noticed I use putty 64-bit for my setup, however if you use 32-bit in the settings file both:

```
<PscpExe>\Program Files\PuTTY\pscp.exe</PscpExe>
```
```
<PuttyExe>\Program Files\PuTTY\putty.exe</PuttyExe>
```

Can be set to

```
<PscpExe></PscpExe>
```
```
<PuttyExe></PuttyExe>
```

And on firstrun they will be auto-populated
