### ISSUE TITLE
SPSL script starts when session is opening.

### ISSUE THREAD

**Issue by erlnikolay** [jimradford/superputty#683]
Hello Jim.

Please explain why SPSL script starts at the same time when session start?
I can't do log in because script sctarts at the same time.
I configured SPSL script as:
SLEEP 10000
But It is not comfortable because I should enter log in information (log name and password) in 10 second. I can't enter log in information in session configuration because we have system with SafeWord Password (random code passowrd).
Please could you explaine how to do that script SPSL starting after connection is finished.

And if it is impossible please can you create new realse with two checkboxes inconfig session such as "start script imediatelly" and "start script after compleated connection". It will be helpfull.

Best Regards,
Nikolay

**Comment by jimradford** [comment]
Hi @erlnikolay ,

SPSL is not (yet) event driven, it is simply a batch processor. It does not yet have support for getting any status information from putty itself, e.g. when a connection has occurred. It does not know about that happening. 

It might be possible to make it behave more like http://expect.sourceforge.net/ Expect but there is no current roadmap. 

Regards,
Jim
