### ISSUE TITLE
superputty not launching 

### ISSUE THREAD

**Issue by aldowski** [jimradford/superputty#701]
Hi all;
SuperPuTTY-1.4.0.8 not launching. Nothing in taskbar, nothing in task manager. Nothing on screen after start (I mean, no error messages, no windows, dialog boxes, nothing).
I tried both installed and portable versions, nothing works.
I am using Windows 7, have Microsoft NET Framework 4.6.2. Tried few compatibility modes (properties of the app), tried to start with or without administrator mode. 
I have basic Putty installed, working, no issues. 
There are few similar problems mentioned in issues listing, with no exact answer, no solution at the end. What can be checked, what would be next step in order to make it running?
Thanks.

**Comment by jimradford** [comment]
Can you look at the logfile and see if it contains any useful hints? 

https://github.com/jimradford/superputty/wiki/Troubleshooting 

Jim

**Comment by jimradford** [comment]
Great to hear you were able to get it resolved. I've updated the Troubleshooting document to suggest renaming or deleting the SuperPutty.settings file.
