### ISSUE TITLE
Next release ?

### ISSUE THREAD

**Issue by Stef-33560** [jimradford/superputty#703]
Hi :)

Le latest stable SuperPuTTY Release is 1.4.0.8 (26 Oct 2015) ; 79 commits to master have been done since. If the project is not abandonned, when will be released the new version ?

Thanks a lot :)

Regards, 
Stef

**Comment by snowzach** [comment]
I think there was some automated builds but they expire after 6 months... So the latest available is the 2015 version... @jimradford  any chance you could trigger a build or create another release?

**Comment by jimradford** [comment]
Yup! Will do and thank you for the information re: Expiration.

**Comment by snowzach** [comment]
Awesome thanks!
