### ISSUE TITLE
Feature request: Remote command

### ISSUE THREAD

**Issue by achinayoungwaubonsee** [jimradford/superputty#704]
In PuTTY, the only way to run a remote command is define a session with am embedded remote command (Connection->SSH->Remote command). I would like to run a remote command for *every* host I configure in SuperPutty. The remote command is simple, root@<host>. However, I really don't want to have to create a Putty session for every host. When creating a new session in SuperPutty, is there any way to add the option to execute a remote command without having to create a new PuTTY session?

**Comment by larsen0815** [comment]
Could you please explain a little bit more, what you are trying to achieve with this?
Perhaps you want to check out Saltstack for executing a command at multiple hosts.

**Comment by achinayoungwaubonsee** [comment]
I was able to find a solution to what I wanted using normal Putty.
