### ISSUE TITLE
SuperPutty stops at password prompt when invoked with command line

### ISSUE THREAD

**Issue by TragicWarrior** [jimradford/superputty#706]
I have consulted the built-in help and have tried to invoke SuperPutty in two different ways.  In each case, the remote system is waiting for the password to be supplied.  Here are the two different invocation methods.

```
SuperPutty.exe -SSH -P 22 -l <user> -pw <pass> 172.16.0.1

SuperPutty.exe -l <user> -pw <pass> ssh://172.16.0.1:22
```
I am also testing against 2 separate Linux systems Ubunut 16.04.5 and Centos 7.  The behavior is the same on both target systems and invocation methods.

**Comment by jimradford** [comment]
I believe the best (and most secure) way is to use ssh Keys instead of a cleartext password (which will continue to show in your local process list). That being said I do not recall if there is any better support for that method of invocation from the command line.

**Comment by jimradford** [comment]
To be able to use the passwords on the command line or in a session you must check the box "Allow plain text passwords on putty command line" in Tools -> Options -> Gui under security
