### ISSUE TITLE
Save Password

### ISSUE THREAD

**Issue by saurabhsharma001** [jimradford/superputty#713]
I just updated to version 1.4.0.9 and it stopped allowing me the "-pw" to store password in the Extra PuTTY arguments text box. 
The text box turned RED and terminal asks for password again.

**Comment by saurabhsharma001** [comment]
Found another issue reported for the same issue: #706
closing this one.

**Comment by TechStuffBoy** [comment]
Hey Guys,

I know this thread is closed, but thought it might be useful for the future crawlers.

I am in SuperPuTTY Version: 1.4.0.9,
While storing sessions, Just in extra arguments window, give your server's password
ExtraArgs="-pw pass123"

It will appear in red color, but don't worry, go ahead and save it.

From this time, u can just click on the session and the password will be entered automatically for you.

![image](https://user-images.githubusercontent.com/17155643/81402028-3facfe80-914e-11ea-8ad8-4e2198b3eb44.png)

Only problem is that, this password is going to be stored in your session file as a plain text.
Location of session file is,
C:\Users\[user_name]\Documents\SuperPuTTY\sessions.xml

If you are fine, then go ahead.

Happy coding, Happy Learning.

**Comment by janwarming** [comment]
the pw argument works fine if i call putty from a shortcut, but no password is inserted if i do it like displayed here.

**Comment by gnetanel** [comment]
@janwarming 
Make sure you have have done the below:
at 
Tools -> Options -> Gui,
under security, check the checkbox... 

I had the same issue and after doing the above password auto fill start to work for me..

**Comment by jdgh000** [comment]
hi I am following up on here, following previous posts, i got to stored password successfully. However is there a way to specify priv/pub key to do automatic connection? Thx
