### ISSUE TITLE
Not compatible with Putty0.71

### ISSUE THREAD

**Issue by BigNuoLi** [jimradford/superputty#735]
**Describe the bug**
After upgrade the Putty to 0.71, open the existing saved session will not show the Putty in the windows.

**To Reproduce**
1. save a session created with prior version of Putty by SuperPutty
2. close SuperPutty
3. upgrade Putty to 0.71
4. open SuperPutty, and double click the saved session
5. you should get the issue (No putty section shown) 

**Expected behavior**
The SuperPutty can work with Putty0.71

**Desktop (please complete the following information):**
 - OS: windows 10
 - Putty : 071

**Comment by Zaczero** [comment]
Well for me it works fine but there are small glitches

![](https://i.imgur.com/AtHBGKj.png)

My connection settings:

![](https://i.imgur.com/3jSUDor.png)

**Comment by BigNuoLi** [comment]
Thanks.
I have some further checking and find that, the issue I got is not related with SuperPutty, but the Putty 0.71 cannot run on my desktop.
And maybe because of the security settings in my windows 10 block new version of Putty to run.
