### ISSUE TITLE
-pw password is not working. Still asking for password with putty 0.71

### ISSUE THREAD

**Issue by ketanpatil3** [jimradford/superputty#739]
-pw password is not working. Still asking for password with putty 0.71

**Comment by ananttickoo** [comment]
I am also facing same issue after getting latest putty.

**Comment by jimradford** [comment]
Check the options dialog  in superputty to ensure the checkbox to allow unsecure passwords on the command line is checked.

 

Jim

**Comment by ananttickoo** [comment]
@jimradford  that for the help . It worked, i think upgrade might have reset the option.

**Comment by JerryChin** [comment]
Bumped into this problem with v1.4.0.10, It takes me a while to find the option mentioned above, it is located at `Options > GUI > Security`, how odd is that!
