### ISSUE TITLE
Adding a user/password to autologin

### ISSUE THREAD

**Issue by greavette** [jimradford/superputty#748]
SuperPutty version 1.4.09

Hello,

I'm new to SuperPutty.  Is there a way to save a user and password with which to login to each SSH session?  I'm using SuperPutty to connect to more than one server at a time and I would like to have the ability to auto login to each server over ssh using a default username and password.

Is this feature available?

Than you.

**Comment by greg-michael** [comment]
Pre-share your SSH key with the servers.

**Comment by greavette** [comment]
That'll work! Thank you for the reply.
