### ISSUE TITLE
SSH login using private key

### ISSUE THREAD

**Issue by rajeeshckr** [jimradford/superputty#752]
**Is your feature request related to a problem? Please describe.**
Looks like there is no way to login to a machine using private key. That would be great to have.

**Describe the solution you'd like**
After the login and password text box, a file finder to select the private key.
Or a drop down of login options  - using username - using private key.

**Comment by waukeerules** [comment]
This would be a feature existing in PuTTY or KiTTY. I typically create a session which contains my username and private key. When I want to use it, I simply select it from the drop down menu.

**Comment by greg-michael** [comment]
In PuTTy:
Load you Default settings

  *   Make whatever changes you like to customize your profile, most importantly, in the Connection -> SSH -> Auth section, add you private key file generated from Pagent or whatever other tool used to generate your private key
Save your settings as a different name, for example: Default-Rajeeshckr

* This assumes you are logging into a *Nix based OS *

Open Super PuTTy and create a new session

  *   In the PuTTy Session Profile, select your newly created profile (Default-Rajeeshckr)
Save and connect to your new session
Accept defaults for server certificate if prompted
Login as normal with user/pass
Run ssh-keygen and generate a local private key (this does not need to be done each time, but assures that the permissions are set properly)
Paste your PUBLIC key that you created (when you generated the private key) into the ~/.ssh/authorized_keys file.

Once you’ve shared your public key with your hosts and stored it in the ~/.ssh/authorized_keys file, you will not have to enter your user/pass when logging in.  I do this on every Linux box I touch.

**Comment by rajeeshckr** [comment]
Thanks guys, will try these out!

**Comment by rbeede** [comment]
I currently use the -i method, but it would be nice to have a convenient GUI control that let me pick the ppk file instead.

**Comment by jimradford** [comment]
Added the information above to the SuperPuTTY documentation Wiki for future generations.
