### ISSUE TITLE
Import Sessions from File - confirm how many putty windows have been opened

### ISSUE THREAD

**Issue by greavette** [jimradford/superputty#760]
Hello Team,

Great product here!  Thanks very much for making this available to us!

I have a question around confirming how many putty windows have been opened. I have a usecase whereby I'm opening around 90 putty windows.  To confirm that my input file I created was done properly I cycle through each putty window (I've setup Function keys to NextTab and PreviousTab in shorcuts) and I count each window.  Is there a better way to do this?  Is there something in Superputty that will tell me how many opened putty windows I have opened?

Thank you in advance for any guidance you can provide me.

**Comment by gmacgregor1** [comment]
Ive run into something similar to this, and I discovered the switch session option. 
under File, Switch Session.  The new window that shows up tells you the number of session tabs that are opened in the window name ie `Switch Session [X]`

Hope this helps :)

**Comment by greavette** [comment]
@gmacgregor1 you are awesome!  Thanks very much for suggesting this to me.  This will work perfectly for me.  

Have a great day!
