### ISSUE TITLE
Alt key sticks in Windows 10 

### ISSUE THREAD

**Issue by zidercol** [jimradford/superputty#766]
**Describe the bug**
I have superPutty on windows 10 (1809). When I send window to the background (only minimize it ) and then bring it back I always see how SuperPutty window hang up for a 5-10 seconds. After this I usually catch KeyboardEvent.altKey state change. This hung operation programmatically changing state of the Alt key! I tried all version since 1.4.0.4 until 1.4.0.9. May it depend from anything else ? 

**To Reproduce**
1. Open SuperPutty on Windows 10.
2. Activate some other window and send supper putty to background. You need to minimize window (initiate redraw). I tried just open something above superputty and didn't catch hung ups.
3. Maximize superputty window 

**Expected behavior**
No hung ups
![putty](https://user-images.githubusercontent.com/35635354/65509089-17d49780-deeb-11e9-9f06-b7cf6d69e476.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10 1809

**Comment by zidercol** [comment]
**Suggestion**
I found that Microsoft Edge saved a lot of PDF files, because it is default PDF reader. Edge didn't release previously opened files between PC reboots in current config. But after all in task manager I see a lot of unused RAM. Duration of the hung up is depend from the count and size of the opened PDF file in Microsoft Edge. I catch problems after 30 opened PDF files in 2 Edge windows. May be SuperPutty have problem with memory using in Windows 10 ? 

![putty](https://user-images.githubusercontent.com/35635354/65515003-e4e4d080-def7-11e9-83ec-2d89d6b19c35.PNG)

**Comment by minakitty** [comment]
I've been having a similar, but not necessarily exact issue for the last few months on 1.4.0.8.  If I alt-tab back into the window, on occasion the Alt key will 'stick', try to open dropdown menus or treating my console inputs as though I was holding the Alt key at the same time.  I was thinking I had a bad switch in my keyboard until I realized it only ever happened when I was working around this app.  Pressing Alt on my keyboard refreshes the information and unsticks the key, so it's not game breaking, but it -does- put a hamper on workflow.

**Comment by zidercol** [comment]
> Pressing Alt on my keyboard refreshes the information and unsticks the key.

When you are working with production servers or if you have some hotkeys it is very sufficient random factor. Any way I resolved my problem by freeing up memory used by Microsoft browsers.
