### ISSUE TITLE
Script Editor Problem

### ISSUE THREAD

**Issue by ajaznawaz** [jimradford/superputty#768]
Works for my colleague, but not for me.

Trying to send commands across multiple sessions concurrently. In my case script editor only sends to session tab currently displayed.

If i 'spread' my tabs across the screen like 'tiles' then it works...

Very strange.

**Comment by waukeerules** [comment]
I think you have "Send To Visible Tabs Only" enabled. Take a look at my screenshot - it might be helpful.

![image](https://user-images.githubusercontent.com/12787084/67991506-76d2ae00-fc07-11e9-91ff-38353fd453de.png)

**Comment by ajaznawaz** [comment]
Hi Jimradford/Superputty
That works for me !
thank you very much indeed !!!
