### ISSUE TITLE
Add "prompt for input" support in spsl

### ISSUE THREAD

**Issue by mrklc** [jimradford/superputty#774]
**Is your feature request related to a problem? Please describe.**
When implementing auto login via spsl, if it is a user name / password authentication, there is no choose but have to put the password into the spsl script, which has a security issue.

**Describe the solution you'd like**
To avoid putting sensitive information like password into the script, implementing a special command to trigger a user input dialog that prompts user to enter the password shall resolve the problem.  In addition, it is useful in scenarios that require interaction with user dynamically. 

**Describe alternatives you've considered**
Encrypted variable

**Additional context**
nil

**Comment by jimradford** [comment]
Keep in mind, this will halt script execution until something is entered.
