### ISSUE TITLE
Hot-key to switch between tabs (similar to ALT-TAB for switching between applications)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#8]
```
I love the dockable tabs to consolidate the multitude of terminal sessions 
that I can be working in over the day but find myself trying to quickly 
switch back to the last session only to find some other application in my 
face.  If I had an alternative, I'm sure I could break the bad habit of 
using Alt-Tab to go to another window.

Firefox uses Ctrl-Tab to go forward a tab and Ctrl-Shift-Tab to cycle 
backwards - something similar would be grand.
```

Original issue reported on code.google.com by `adriangw...@gmail.com` on 5 May 2010 at 11:23

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!

**Comment by ndattani** [comment]
In the above comments, it seems that CTRL+HOME/END (a very bizarre choice compared to CTRL+PgUp/PgDn) has been implemented for switching tabs. However, I just installed putty and superPutty on my new computer today, and CTRL+HOME/END does not work. How do I get it to work?

**Comment by Whichcraft** [comment]
@ndattani 
tools -> options -> shortcuts -> there you can activate it

**Comment by ndattani** [comment]
@Whichcraft : Thank you. I don't use super-putty anymore.

**Comment by mugenishere** [comment]
What is this bullshit? Why is this not being fixed? it's been almost a decade and still this isn't fixed. What a lousy QA who cannot reproduce such a simple and direct issue! I've been tolerating this nonsense for a decade at work. Fuck you!

**Comment by jimradford** [comment]
An uninstaller is provided (and has been for a decade).

**Comment by mugenishere** [comment]
Except for the alt-tab, the app is brilliant.

Also, I'm sorry for my earlier comment. I was working on multiple tasks and
encountering the alt-tab problem every minute, for more than an hour.

Mugen
