### ISSUE TITLE
Settings are stored in incorrect location due to SuperPutty.Utils.PortableSettingsProvider not being specified

### ISSUE THREAD

**Issue by AndrewJoncas** [jimradford/superputty#806]
**Describe the bug**
The provider "SuperPutty.Utils.PortableSettingsProvider" is not specified as the provider for all settings. This causes SuperPutty settings to be saved to the users profile instead of the SuperPutty.settings. This causes external application paths such as FileZilla or WinSCP to be lost when SuperPutty is used on portable storage.

Settings Affected:
PscpHomePrefix
AutoUpdateCheck
PscpRootHomePrefix
Action_OpenScriptEditor_Shortcut
SessiontreeShowFoldersFirst
FileZillaExe
WinSCPExe
PersistCommandBarHistory
AllowPlainTextPuttyPasswordArg
PuttyDefaultParameters
SaveCommandHistoryDays
CommandBarHistory

**To Reproduce**
1. Open SuperPutty 
2. Tools Options
3. Enter FileZilla path
4. Notice that the FileZilla path is stored in:
%UserProfile%\AppData\Local\http___www.jimradford.com\SuperPutty.exe_Url_...\1.4.0.9\user.config
instead of:
SuperPuTTY.settings (independent of the settings being in the user profile root or application folder)

**Expected behavior**
user.config file should not be generated and all settings should be stored in SuperPuTTY.settings

**Screenshots**
![image](https://user-images.githubusercontent.com/29053424/86836535-a164e880-c06b-11ea-8069-82ac61e55a1c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
When built with "SuperPutty.Utils.PortableSettingsProvider" specified as provider for all settings, the application works and stores settings as expected.

**Comment by jimradford** [comment]
Thanks for the report, the fix has been comitted.
