### ISSUE TITLE
I can't start superputty from the configuration file SuperPutty.exe.config

### ISSUE THREAD

**Issue by ortiga88** [jimradford/superputty#813]
I edit the configuration file SuperPutty.exe.config the attribute:

```
<setting name = "ExitConfirmation" serializeAs = "String">
         <value> False </value>
```

I start supperputy and close and I keep getting the confirmation message, I don't understand, I have also tried changing it in the SuperPuTTY.settings but nothing

**Comment by Chealer** [comment]
Can you clarify what you mean by "starting superputty from [a] configuration file"? Do you mean you can't get SuperPuTTY to use that file as configuration?

**Comment by ortiga88** [comment]
yes

**Comment by jimradford** [comment]
SuperPutty.exe.config is used to configure logging and other internal stuff, and should probably never need to be edited. SuperPutty.settings contains all user specific settings.

The Wiki has a new section about the actual configuration file locations.

**Comment by Chealer** [comment]
I have got to grant that "SuperPutty.exe.config" is quite a strange file name. I understand that the existence of another configuration file complicates naming, but I'm sure something better than that can be found.

**Comment by jimradford** [comment]
@Chealer I know, but its how Microsoft decided to do things.

**Comment by Chealer** [comment]
Oh; wow, I had never noticed that. Apologies for the comment and thanks @jimradford

**Comment by jimradford** [comment]
@Chealer No worries. I've never been a fan of how that is done, it can be changed, but would be more cumbersome than its worth.
