### ISSUE TITLE
Using Superputty.exe.config file

### ISSUE THREAD

**Issue by Octavius83** [jimradford/superputty#822]
When launching SuperPutty.exe for the first time as a new user, I'd need to have the path to putty.exe pre-populated.  I've added it into the SuperPutty.exe.config file, but settings in here don't seem to have any effect.  Do I need to call the config file when running the executable to load the settings?

```
      <setting name="PuttyExe" serializeAs="String">
        <value>C:\Program Files\PuTTY\putty.exe"</value>
      </setting>
```

Is this what the SuperPutty.exe.config file is for?  If not, is there any other way to pre-configure the setting?

This is a fresh installation of SuperPutty 1.4.0.9 running on Windows Server 2012 R2

**Comment by jimradford** [comment]
This should now work as expected, you can pre-populate the SuperPutty.config file with settings and they should be picked up on first load. Previously there was a bug that could have allowed the settings to be stored in multiple locations. Fixed as of commit: https://github.com/jimradford/superputty/commit/01df6cc2399017c0e149aeec3a6a3c20ecb44859

The Wiki has a new section about the actual configuration files locations.

**Comment by bhball22** [comment]
When using version 1.5.0.0 this functionality is no longer working. I am trying to turn off some flags and adding similar settings that the user above has tried.

This is being installed on a fleet of workstations running Windows 10 and in the future we are going to be installing on enterprise Windows 11.
