### ISSUE TITLE
Request to update to a standard OSI license

### ISSUE THREAD

**Issue by ragujayaraj** [jimradford/superputty#827]
**Is your feature request related to a problem? Please describe.**
This is very cool tool and I love it. But, tool is giving some non-standard license text and not using the industry accepted license terms. Because of that some people like me will find it difficult to use this tool at work.

**Describe the solution you'd like**
Hence the request is to update the license text to one of the industry accepted OSI licenses (refer https://opensource.org/licenses/alphabetical)

**Describe alternatives you've considered**
Not applicable

**Additional context**
Not applicable

**Comment by Chealer** [comment]
SuperPuTTY is already available under the MIT License. Perhaps there is a way to clarify that, though.

**Comment by jimradford** [comment]
It is the MIT License, word for word, not exactly sure what is being asked here? 

https://choosealicense.com/licenses/mit/
