### ISSUE TITLE
growing huge unused area in UI between tabs and terminal emulation

### ISSUE THREAD

**Issue by KlausThornProgrammfabrik** [jimradford/superputty#831]
Suddenly there is a big unusable UI area which "pushes" the terminal area down (see screenshot, marked in red) so that the last few lines of the terminal are not visible any more.

This unusable area multiplies its (initial) size with events like Alt+Tab or clicking on the upper border of the terminal area, until the terminal is not visible at all any more :-O

Changing tabs resets the unusable area to the initial (still big) size.

More variants: When I detach a tab into its own window and make it the active window (top border changes color) and click on the terminal area (or resize the window), it even happens in two dimensions: There is a big unusable area from above and from the left, see 2nd screenshot.

**To Reproduce**
1. open superputty
2. start any putty session from the session list
3. Alt+Tab OR click on Superputty top window border and then back into terminal area
4. huge unusable UI area appears

**Expected behavior**
No unusable UI Area appears

**Screenshots**
<img width="384" alt="growing_grey_area" src="https://user-images.githubusercontent.com/14091833/114568757-b44cbf00-9c74-11eb-820d-d497d684b57e.png">

detached window:
<img width="723" alt="growing_grey_area_detached_window" src="https://user-images.githubusercontent.com/14091833/114569261-1a394680-9c75-11eb-8790-b490e5a787b9.png">

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 64bit
 - Version SuperPuTTY: 1.4.0.9
```
mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
SuperPutty, Version=1.4.0.9, Culture=neutral, PublicKeyToken=null
log4net, Version=1.2.13.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a
System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
WeifenLuo.WinFormsUI.Docking, Version=2.9.0.0, Culture=neutral, PublicKeyToken=5cded1a1a0a7b481
System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Microsoft.GeneratedCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
System.Runtime.Remoting, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
System.Windows.Forms.resources, Version=4.0.0.0, Culture=de, PublicKeyToken=b77a5c561934e089

```

**Comment by KlausThornProgrammfabrik** [comment]
reboot of Windows resolved the problem for me

**Comment by sibko** [comment]
the same issue has now started happening to me this week, same os and version as above, did you find any solution besides restarting?

**Comment by KlausThornProgrammfabrik** [comment]
> the same issue has now started happening to me this week, same os and version as above, did you find any solution besides restarting?

nothing yet. Happened to me four times now.

**Comment by KlausThornProgrammfabrik** [comment]
Maybe there is a connection with slack (chat client). The symptoms of this bug started to appear (at least today) when sharing my browser-window and after that my superputty window during a slack video group call.

Quitting slack (not just closing the window but stopping the whole app via its file menu) made the symptoms go away.

Side note:
Also notepad++ was affected by symptoms (window was not visible a.k.a. did not come into foreground; when restarting notepad++, its size was reduced to just the tree window-buttons minimize,maximize,close).

**Comment by KlausThornProgrammfabrik** [comment]
Happens often (not certain whether it happens always):
1. start superputty
2. start slack video conference
3. share my screen during the conference (browser window, not even superputty)
4. finish video conference
5. switch back to superputty -> issue is there (unusable UI area)

Workaround: Reboot (2 out of 2 tests) or quitting slack (2 out of 2 tests)

**Comment by sibko** [comment]
> 
> 
> Maybe there is a connection with slack (chat client). The symptoms of this bug started to appear (at least today) when sharing my browser-window and after that my superputty window during a slack video group call.
> 
> Quitting slack (not just closing the window but stopping the whole app via its file menu) made the symptoms go away.
> 
> Side note:
> Also notepad++ was affected by symptoms (window was not visible a.k.a. did not come into foreground; when restarting notepad++, its size was reduced to just the tree window-buttons minimize,maximize,close).

yeh same for me, definitely seems to be slack, i've moved to mobaxterm and whilst terminal windows arent affected its rdp windows are in a similarly strange way
