### ISSUE TITLE
SuperPutty throws exception when you click 'OK' in the initial configuration screen for lastest branch fresh install

### ISSUE THREAD

**Issue by LCruel** [jimradford/superputty#837]
**Describe the bug**
SuperPutty throws exception when you click 'OK' in the initial configuration screen, after you have set the putty.exe location.

**To Reproduce**
1. Go to gitlab, clone latest code
2. Compile 
3. Install
4. Start SuperPutty
5. Select putty.exe
6. Click 'OK 
7. Application throws exception
OR
1. Go to gitlab
2. Download artificets from last build ('https://ci.appveyor.com/project/jimradford/superputty/branch/master/artifacts")
3. Install
4. Start SuperPutty
5. Select putty.exe
6. Click 'OK 
7. Application throws exception

Note: This only happens when you have not previously had SuperPutty installed. The last merge that did work correctly (for me) was 'Made the application DPI aware #816 by bjansen was merged on 18 Nov 2020'. 

Workaround is to install older branch or release of SuperPutty run the program for the first time and set putty.exe and click OK in the configuration screen. Then replace installed files with the latest build (all files) in X:\Program Files (x86)\SuperPuTTY.

Note: Windows protection marks each file untrusted and you need to unblock them by opening the file properties and removing the check mark for each file.

**Expected behavior**
SuperPutty to start after the initial configration is set.

**Desktop (please complete the following information):**
 - OS: Win10

**Additional context**

**Comment by jimradford** [comment]
Yes, a screen shot of the exception would be execptional!

**Comment by jimradford** [comment]
Ok this was being caused due to the default values not being properly set when using the portable settings provider.

**Comment by LCruel** [comment]
Hi Jim,

You beat me to uploading a picture, I can confirm that the new release now works on a blank machine.

Regards,
Daniel

**Comment by jimradford** [comment]
@LCruel Thank you for the confirmation and the report.

Regards,
Jim
