### ISSUE TITLE
PuTTY Default Parameters documentation

### ISSUE THREAD

**Issue by Chaffy-0** [jimradford/superputty#842]
I couldn't find any reference to the PuTTY Default Parameters in the documentation.  Is that covered somewhere else?  Is this where you can set specific Putty settings for your sessions?  i.e. logging, appearance, colours, etc...

**Comment by 4SiB** [comment]
+1

And I cannot use a GNS3 with a -wt "Windows Title" !

**Comment by jimradford** [comment]
Documentation for logging of superputty is no win the wiki, for anything putty specific you should check putty's documentation. If you configure a session and save any preferences, you can load those preferences by selecting them in the SuperPutty sessions editor where you can select the PuTTY session profile.

PuTTY documentation is here: https://www.chiark.greenend.org.uk/~sgtatham/putty/docs.html
