### ISSUE TITLE
it's impossible to clean up tabs in the top bar

### ISSUE THREAD

**Issue by buciski** [jimradford/superputty#843]
**Describe the bug**
as you can see into screen attached, i can't delete/close two tabs into top bar menu

I can use normally superputty, since a new bar below is open

<img width="491" alt="tab_issue" src="https://user-images.githubusercontent.com/36300091/141474476-50abbc48-31a1-49af-b857-caba851b96ab.PNG">

**Comment by jimradford** [comment]
Please Try Help -> Diagnostics -> Clean up Stray Processes and report back if that does or does not clean up the inactive sessions.

**Comment by buciski** [comment]
**Clean up Stray Processes** do not solve the issue, even if those tho tabs are marked as _inactive_

SuperPuTTY version: 1.4.0.9

**Comment by jimradford** [comment]
What caused them to become inactive to begin with?

**Comment by buciski** [comment]
well, i don't know exactly how, I was playing with bars/views and it happened -  and now I cannot hide/delete that bar of inactive sessions.

do you have any hints?

**Comment by jimradford** [comment]
In the Settings Folder (You can see location by pressing F2 -> Settings Folder) there should be a file called AutoRestoreLayout.XML, delete that file and see if it clears up your issue.
