### ISSUE TITLE
Add support for Ctrl + Right/Left

### ISSUE THREAD

**Issue by abousselmi** [jimradford/superputty#849]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

When I hit Ctrl + Right Arrow or Ctrl + Left Arrow keys, the cursor would move between words.

**Describe alternatives you've considered**

If the word (part of the command) that I need to modify is close enough to the beginning of the line, I use Ctrl + a, if not, then I simply move the cursor (generally using the left arrow) one character at a time (which is really painful if the command is too long..

**Additional context**

No.

Thanks

**Comment by jimradford** [comment]
Hi @abousselmi is this request for when you are inside an open terminal (ssh connection) to a remote server?

**Comment by abousselmi** [comment]
Hi @jimradford 
Yes exactly.

**Comment by jimradford** [comment]
@abousselmi This is something that would have to be done inside putty itself. SuperPuTTY would be unable since its a separate process and we don't have access to the terminal (other than write of course).

Regards

**Comment by marbaa** [comment]
Use Kitty instead putty. It contains such feature.

**Comment by jimradford** [comment]
@marbaa Thanks for the suggestion! Very useful to know.

**Comment by abousselmi** [comment]
Thanks @marbaa and  @jimradford , very useful indeed.
