### ISSUE TITLE
Release mixed up

### ISSUE THREAD

**Issue by AntonOks** [jimradford/superputty#853]
https://github.com/jimradford/superputty/releases/tag/1.4.10 somehow mixes up with 1.4.**0**.10

**Comment by jimradford** [comment]
Yup, I tagged it wrong. The assembly version is correct.

**Comment by AntonOks** [comment]
... not it keeps asking if one wants to update!

**Comment by jimradford** [comment]
You can turn that off in preferences for now. If you are using that tagged release it shouldn't be asking to update?

**Comment by dofuuz** [comment]
@jimradford I think next version should be 1.4.11 or 1.4.11.0, to avoid confusion with version sorting.
