### ISSUE TITLE
SHA1 Support

### ISSUE THREAD

**Issue by kaj0103** [jimradford/superputty#867]
Sorry if this is not how to ask this, but I can find no other way.

It is not a problem fix. It's a query.

Hi. I work for a large org. We have 1.4.0.9 currently. I am trying to find a defniitive answer somewhere as to whether it supports SHA1 hashing. I am looking for a way to prove to upper management that a user will not be able to use SHA1 in the encryption suite.

Guidance would be greatly appreciated.

Thank you.

AK

**Comment by jimradford** [comment]
SuperPutty does not support any hashing or encryption itself. This would be a function of putty. I would inquire here: https://www.chiark.greenend.org.uk/~sgtatham/putty/ for further assistance.
