### ISSUE TITLE
Download SupperPuTTy

### ISSUE THREAD

**Issue by hwprinz** [jimradford/superputty#876]
Hi, 
I understand to get the latest 1.4.10 version as described in the home section/Read.me

non the less is there some misleading stuff in the Wiki Homepage 
it says 'for more information see our [Download SuperPuTTY] Page'

If you go there, you find:
SuperPuTTY is available in both Binary and Source Form from our [GitHub project page](https://linkify.me/GueknjO)
-> this linkify is not existing

as well: if you public google 'Download Superputty'
you first get to https://www.puttygen.com/superputty#SuperPuTTY_download
don't know, if this is as well in your hands
...just wanted to say..

all not a bug issue, but confusing.....
/hans

**Comment by jimradford** [comment]
That is somebody elses page (puttygen), so I can't assist in them causing confusion
