### ISSUE TITLE
New version?

### ISSUE THREAD

**Issue by Neustradamus** [jimradford/superputty#887]
Dear @jimradford and SuperPuTTY team,

It is possible to have a new release build one year after?

The last 1.4.0.10 (2021-11-22):
- https://github.com/jimradford/superputty/releases

And there is always a message about an update for 1.4.10.

Thanks in advance.

**Comment by yenseaman** [comment]
In %USERPROFILE%\SuperPuTTY.setting
can disable version check by modifying  AutoUpdateCheck to False
 `<AutoUpdateCheck>False</AutoUpdateCheck>`
Reference:  #675

**Comment by jlanzarotta** [comment]
I have added new icons and an notes field.  It would be nice to have a new version, but after a year, I doubt there will be a new version.  Has this project been abandoned?  Not sure... I just use my own version unfortunately...

**Comment by jimradford** [comment]
Fixed in Release 1.5.0.0

**Comment by Neustradamus** [comment]
@jimradford: Thanks a lot and Happy New Year 2023!
