### ISSUE TITLE
Version 1.4.10 shows as 1.4.0.9 in the registry

### ISSUE THREAD

**Issue by LeeViewB** [jimradford/superputty#888]
**Describe the bug**
Version 1.4.10 shows as 1.4.0.9 in the registry

**To Reproduce**
1. Install 1.4.10
2. Registry will show prev version

**Expected behavior**
Should show 1.4.10

![2g](https://user-images.githubusercontent.com/31350302/200277566-a08efe60-e192-49d6-a53d-943c76de7324.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 and 11

**Additional context**
When distributing the app using a management solution, the wrong DisplayVersion will cause detection issues.

**Comment by gunnarhaslinger** [comment]
As it is noted ad 1.4.0.9 in the Registry it shows up as 1.4.0.9 in Control-Panel -> Software.

And it gets even worse: In SuperPuTTY -> Help -> About SuperPuTTY ... shows 1.4.0.8

So please fix, not ideal to get out what Version is really running because of this misleading information.

**Comment by jimradford** [comment]
Fixed in Release 1.5.0.0
