### ISSUE TITLE
During upgrade older versions are not removed.

### ISSUE THREAD

**Issue by LeeViewB** [jimradford/superputty#889]
**Describe the bug**
Even though previous releases share the same UpgradeCode, when a newer version is installed, older versions are not removed.

**Comment by jimradford** [comment]
From which to which version are you experiencing this? I was not able to recreate the issue as described.

**Comment by LeeViewB** [comment]
It was some older versions. Looks like n-1 upgrades just fine to n atm. Will mark the issue as closed
