### ISSUE TITLE
Missing SuperPuTTY x64 release build (64bit/64 bit)

### ISSUE THREAD

**Issue by Neustradamus** [jimradford/superputty#894]
Dear SuperPuTTY team, @jimradford,

Thanks for 1.5.0.0 release from today but SuperPuTTY x64 (64bit/64 bit) release build is always missing.

Can you create this important missing release build?

Thanks in advance.

**Comment by Neustradamus** [comment]
@jimradford: Sorry for the delay!

It is like to create 32 bit application because 16 bit works?

You can look information on official PuTTY website:
- https://www.chiark.greenend.org.uk/~sgtatham/putty/faq.html#faq-32bit-64bit

**Comment by jimradford** [comment]
SuperPuTTY, written in .NET doesn't care if you use a 32 or 64 bit version of putty you can use either. Did you read the link I provided?

**Comment by Neustradamus** [comment]
It is time to enter in the future, we are in 2023, x64 is here since Windows XP Pro.
The goal is to have like other softwares, a x64 version in more x86.

Some links:
- https://learn.microsoft.com/en-us/dotnet/framework/64-bit-apps
- https://www.youtube.com/watch?v=2jdH85teO5Q
- https://www.csharp411.com/determine-if-your-c-application-is-64-bit/
- https://www.ibm.com/docs/en/spectrum-symphony/7.2.1?topic=symphony-support-64-bit-applications
- https://www.geeksforgeeks.org/c-sharp-program-to-check-if-operating-system-is-64-bit-os-or-not-using-environment-class/

**Comment by jimradford** [comment]
I think you might not be understanding, for the SuperPuTTY application, there is zero advantage or purpose to having two binary releases, you literally get nothing from it other than the zip file being labeled "64 bit". It does not/will not perform *any* different from what you are downloading, installing, and using right now.

**Comment by Neustradamus** [comment]
@jimradford: I wish you a Happy New Year 2025!

Have you looked for a x64 build?

In more, can you look for ARM/ARM64?

Thanks in advance.
