### ISSUE TITLE
Add Option for Automatic Focus Switching

### ISSUE THREAD

**Issue by c-a-j** [jimradford/superputty#903]
**Is your feature request related to a problem? Please describe.**
I would really like a setting that made switching focus to the visible tab automatic. I can think of a few fringe cases where the default behavior would be useful, but 99.99% of the time I would prefer the focus to switch automatically to the visible tab.

**Describe the solution you'd like**
Add an option to automatically switch focus to the visible tab.

**Describe alternatives you've considered**
Change the default behavior all together and make focus switching automatic. I don't really see many applications for typing in a background terminal. For me, it's not useful at all, only an annoying accident

If I knew C# I'd love to contribute this feature myself. Unfortunately, I don't have the luxury to spend time learning a new language to make a single contribution. Thank you for your consideration. And I love SuperPuTTY!

**Comment by rex-banner** [comment]
Same problem as described here ?
https://github.com/jimradford/superputty/issues/880

**Comment by c-a-j** [comment]
Yes, that seems like the same issue. Thanks. Closing this issue as it is a duplicate.
