### ISSUE TITLE
Settings overwritten with multiple instances

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jimradford/superputty#91]
```
If you have 2 instances open A and B. Change the settings in A and exit 
SuperPutty. Then exit instance B the settings saved with A are lost.

Rob
```

Original issue reported on code.google.com by `roblow...@gmail.com` on 7 May 2012 at 5:37

**Comment by jimradford** [comment]
Closing this issue but all hope is not lost! We still want to help.
See: https://github.com/jimradford/superputty/wiki/Legacy-Imported-Issues on how to help us to help you!
