### ISSUE TITLE
Please support high dpi monitors

### ISSUE THREAD

**Issue by mmcintyre123** [jimradford/superputty#915]
SuperPuTTY does not resize properly on a high dpi monitor.  The controls and text in the interface become so tiny they are almost illegible.  Please provide support for high dpi monitors.

**Comment by pkumarg** [comment]
Hi,

Can you try below:

1. Go to supperPutty icon, right click, choose file location.
2. If step 1) lands you at location "C:\ProgramData\Microsoft\Windows\Start Menu\Programs\SuperPuTTY", then just do setp 1) again on supperPutty icon here.
3. Now you should be at SuperPutty.exe in location "C:\Program Files (x86)\SuperPuTTY".
4. Right click on SuperPutty.exe, and choose Properties.
5. And then follow as per attached image

![ChangedDPISettingsSupperPutty](https://github.com/jimradford/superputty/assets/31144474/e2024d87-eb31-4f2e-941c-5a5971238d1a)

Then try dragging your windows on different monitors and it should adapt scaling and DPI as per monitor.

Please comment here if it doesn't help.

Cheers !!

**Comment by mmcintyre123** [comment]
That worked, thank you!
