### ISSUE TITLE
Add portable version

### ISSUE THREAD

**Issue by Kyogre** [jimradford/superputty#925]
**Describe the solution you'd like**
Add portable mode so user could specify settings folder path as relative (like `./settings`) in `Settings Folder` parameter, thus `%userprofile%\SuperPuTTY.settings` file will always be read from SP's folder, even if user moved SP folder to another location.

**Comment by mariaczi** [comment]
@Kyogre - if you put this config file `SuperPuTTY.settings` in the same folder when you have application exe then this (config) file will be read.

**Comment by Kyogre** [comment]
you are correct! It is working.
